Repository content-services/content-sources-backend, pull requests merged in 2022-08, with the labels that each got.

#67 Refs 105: symlink containerfile for remote podman building
  .gitignore
  mk/docker.mk
Labels: no-qe-needed

#66 Fixes 122: Add validation to Repository update
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/models/repository_configuration.go
  pkg/models/rpm.go
Labels: qe-testing-needed, qe-testing-required

#70 Fixes 142: support cert via env variable
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/test_files/cert.crt
  pkg/external_repos/introspect.go
Labels: qe-testing-needed, Ready for QE

#71 Refs 142: deployment changes for cdn secret
  deployments/deployment.yaml
Labels: qe-testing-needed, Ready for QE

#59 Fixes 94: repo validation api
  api/docs.go
  api/openapi.json
  pkg/api/repository_parameters.go
  pkg/dao/external_resource.go
  pkg/dao/external_resource_test.go
  pkg/dao/interfaces.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/handler/api.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_test.go
Labels: qe-testing-needed, Ready for QE

#69 Fixes 124: Search filter error on URL column
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/handler/repositories.go
  pkg/handler/repository_test.go
Labels: no-qe-needed

#77 Fixes 141: Make account number optional
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/models/repository_configuration.go
  scripts/header.sh
Labels: no-qe-needed

#76 Fixes 113: Daily cronjob to introspect-all
  deployments/deployment.yaml
Labels: no-qe-needed

#79 Fixes 153: add openapi parameters for listRepositories()
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/handler/repositories.go
Labels: bug, qe-testing-needed, Ready for QE

#74 Fixes 148: switch to simple numbered versions
  pkg/config/value_constraints.go
  pkg/dao/repository_test.go
Labels: qe-testing-needed, Ready for QE

#75 Fixes 125: uniqify versions before save
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
Labels: qe-testing-needed, Ready for QE

#81 Fixes 149: Check revision number before introspection
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  go.mod
  go.sum
  pkg/dao/interfaces.go
  pkg/dao/public_repositories.go
  pkg/dao/public_repositories_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
  pkg/models/repository.go
Labels: no-qe-needed

#85 Fixes 164: properly set versions when de-dupeing
  pkg/dao/repository_test.go
  pkg/models/repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#83 Fixes 138: update down migration for new tables
  db/migrations/20220512132042_create_repository_configurations_table.down.sql
Labels: no-qe-needed

#63 Fixes 100: add local linting tools
  .gitignore
  .golangci.yaml
  .pre-commit-config.yaml
  README.md
  build_deploy.sh
  cmd/dbmigrate/README.md
  cmd/dbmigrate/main.go
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  docs/architecture.puml
  mk/includes.mk
  mk/lint.mk
  pkg/config/config_test.go
  pkg/dao/repository_test.go
  pkg/external_repos/external_repos.json
  pkg/handler/repositories.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_test.go
  pkg/seeds/seeds.go
  pkg/seeds/suite_test.go
  scripts/README.md
  test/README.md
Labels: no-qe-needed

#84 Refs 121: introspect one public repo on startup
  deployments/deployment.yaml
Labels: qe-testing-needed

#73 Fixes 119: fix some tests failing on seeded database
  pkg/dao/repository_test.go
  pkg/dao/rpm_test.go
  pkg/dao/suite_test.go
  pkg/handler/repository_test.go
  pkg/models/suite_test.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
Labels: no-qe-needed

#86 Fixes 143: Remove null fields from api responses
  .golangci.yaml
  docs/openapi/Models/api.RepositoryResponseJSON.md
  pkg/api/repository.go
  pkg/dao/repository.go
  pkg/handler/repository_rpm.go
  pkg/handler/repository_test.go
  pkg/models/repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#91 Fixes 168: fix api doc for pkg name search
  api/docs.go
  api/openapi.json
  docs/openapi/Apis/RepositoriesApi.md
  docs/openapi/Apis/RpmsApi.md
  docs/openapi/README.md
  pkg/dao/repository_test.go
  pkg/handler/repository_rpm.go
Labels: bug, qe-testing-needed, Ready for QE

#89 Fixes 145: refactor dao with better naming
  cmd/external-repos/main.go
  pkg/dao/interfaces.go
  pkg/dao/public_repositories.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
Labels: no-qe-needed
