Repository content-services/content-sources-backend, pull requests merged in 2022-09, with the labels that each got.

#93 Fixes 169: Use swag v1.8.4
  mk/swag.mk
Labels: qe-testing-needed

#90 Fixes 167: fix mk/variables.mk config loading
  mk/variables.mk
Labels: no-qe-needed

#87 Fixes 159: Update validation API to support editing
  .vscode/settings.json
  api/docs.go
  api/openapi.json
  docs/openapi/Models/api.RepositoryValidationRequest.md
  pkg/api/repository_parameters.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
Labels: qe-testing-needed, Ready for QE

#94 Refs 170: changed plugin name to "content_sources"
  deployments/deployment.yaml
  pr_check.sh
Labels: qe-testing-needed

#88 Fixes 115: Create authentication middleware
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_rpm.go
  scripts/header.sh
Labels: no-qe-needed

#100 Fixes 174: set default mem/cpu values
  deployments/deployment.yaml
Labels: qe-testing-needed

#96 Fixes 162: Let search packages by uuid
  api/docs.go
  api/openapi.json
  docs/openapi/Models/api.SearchRpmRequest.md
  pkg/api/repository_rpm.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
Labels: qe-testing-needed, Ready for QE

#103 Refs 104: Update clowdapp database name
  deployments/deployment.yaml
Labels: bug

#98 Fixes 172: fix make build and make run rules
  mk/go-rules.mk
Labels: no-qe-needed

#105 Fixes 166: propery validate repomd exists
  pkg/dao/external_resource.go
  pkg/dao/external_resource_test.go
Labels: qe-testing-needed, Ready for QE

#95 Fixes 109: Store and return introspection status metadata
  api/docs.go
  api/openapi.json
  cmd/external-repos/main.go
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  docs/openapi/Models/api.RepositoryResponse.md
  pkg/api/repository.go
  pkg/config/value_constraints.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_config.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/handler/repositories_test.go
  pkg/models/repository.go
  pkg/models/repository_rpm_test.go
  pkg/models/repository_test.go
  pkg/models/suite_test.go
  pkg/seeds/seeds.go
Labels: qe-testing-needed, Ready for QE

#107 Refs 126: switch to redoc for openapi html
  README.md
  docs/openapi/.openapi-generator-ignore
  docs/openapi/.openapi-generator/FILES
  docs/openapi/.openapi-generator/VERSION
  docs/openapi/Apis/RepositoriesApi.md
  docs/openapi/Apis/RpmsApi.md
  docs/openapi/Models/api.GenericAttributeValidationResponse.md
  docs/openapi/Models/api.Links.md
  docs/openapi/Models/api.RepositoryBulkCreateResponse.md
  docs/openapi/Models/api.RepositoryCollectionResponse.md
  docs/openapi/Models/api.RepositoryParameterResponse.md
  docs/openapi/Models/api.RepositoryRequest.md
  docs/openapi/Models/api.RepositoryResponse.md
  docs/openapi/Models/api.RepositoryResponseJSON.md
  docs/openapi/Models/api.RepositoryRpm.md
  docs/openapi/Models/api.RepositoryRpmCollectionResponse.md
  docs/openapi/Models/api.RepositoryValidationRequest.md
  docs/openapi/Models/api.RepositoryValidationResponse.md
  docs/openapi/Models/api.ResponseMetadata.md
  docs/openapi/Models/api.SearchRpmRequest.md
  docs/openapi/Models/api.SearchRpmResponse.md
  docs/openapi/Models/api.UrlValidationResponse.md
  docs/openapi/Models/config.DistributionArch.md
  docs/openapi/Models/config.DistributionVersion.md
  docs/openapi/README.md
  mk/swag.mk
Labels: qe-testing-needed

#108 Refs 173: fix null env for init containers
  deployments/deployment.yaml
Labels: qe-testing-needed, Ready for QE

#106 Fixes 154: Send empty body on delete response
  api/docs.go
  api/openapi.json
  pkg/handler/repositories.go
Labels: no-qe-needed

#78 Fixes 131: support SSL DB Connections
  pkg/config/config.go
  pkg/db/db.go
Labels: no-qe-needed

#80 Fixes 144: remove unused rpm entries more efficiently
  pkg/dao/interfaces.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
Labels: no-qe-needed

#97 Refs 151: Add makefile rules for kafka
  .dockerignore
  .gitignore
  kafka/Dockerfile
  kafka/config/server.properties
  kafka/config/zookeeper.properties
  kafka/scripts/kafka-entrypoint.sh
  kafka/scripts/zookeeper-entrypoint.sh
  kafka/scripts/zookeeper-healthcheck.sh
  mk/includes.mk
  mk/kafka.mk
  mk/meta-kafka.mk
  mk/variables.mk
Labels: qe-testing-needed

#111 Refs 173: define internal service
  deployments/deployment.yaml
Labels: qe-testing-needed

#99 Fixes 165: Set list default sort order (name asc)
  pkg/api/api.go
  pkg/dao/repositories.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/handler/api.go
  pkg/handler/api_test.go
  pkg/models/repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#102 Fixes 163: Add Any version/Any architecture options
  pkg/api/repository.go
  pkg/config/value_constraints.go
  pkg/dao/repository_config_test.go
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
Labels: qe-testing-needed, Ready for QE

#110 Fixes 185: Save revision properly
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
Labels: no-qe-needed

#109 Fixes 75: Add gpg key and metadata verify to repo crud
  api/docs.go
  api/openapi.json
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  db/migrations/20220921110120_add_gpg_key_to_repository_configurations.down.sql
  db/migrations/20220921110120_add_gpg_key_to_repository_configurations.up.sql
  pkg/api/repository.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/dao/suite_test.go
  pkg/handler/repositories_test.go
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
Labels: qe-testing-needed, Ready for QE

#92 Fixes 111: record package count
  api/docs.go
  api/openapi.json
  db/migrations/20220923124812_add_package_count.down.sql
  db/migrations/20220923124812_add_package_count.up.sql
  pkg/api/repository.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_config.go
  pkg/dao/suite_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
  pkg/models/repository.go
Labels: qe-testing-needed, Ready for QE

#117 Fixes 204: bump to echo v4.9.0
  go.mod
  go.sum
Labels: no-qe-needed
