Repository content-services/content-sources-backend, pull requests merged in 2022-07, with the labels that each got.

#43 makefile:add initial documentation and clean up aliases
  .github/workflows/content-sources-actions.yml
  mk/README.md
  mk/alias.mk
  mk/includes.mk
  mk/meta-alias.mk
Labels: no-qe-needed

#40 proposal:configuration which allow to run and debug unit tests from VSCode
  .gitignore
  .vscode/settings.json
Labels: no-qe-needed

#46 Refs 101: update commit format
  .github/workflows/title.yml
  README.md
Labels: no-qe-needed

#49 Fixes 116: Add create response object and openAPI spec fixes
  api/docs.go
  api/openapi.json
  pkg/api/repository.go
  pkg/dao/interfaces.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/handler/repositories.go
  pkg/handler/repository_test.go
Labels: qe-testing-required

#42 Fixes 47: add api for listing rpms in a repository
  .gitignore
  api/docs.go
  api/openapi.json
  cmd/dbmigrate/main.go
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  go.mod
  go.sum
  mk/db.mk
  pkg/api/repository_rpm.go
  pkg/dao/interfaces.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/dao/suite_test.go
  pkg/handler/api.go
  pkg/handler/repository_rpm.go
  pkg/models/base.go
  pkg/models/repository.go
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
  pkg/models/repository_rpm.go
  pkg/models/repository_rpm_test.go
  pkg/models/repository_test.go
  pkg/models/rpm.go
  pkg/models/rpm_test.go
  pkg/models/suite_test.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
  pkg/seeds/suite_test.go
  scripts/header.sh
Labels: no-qe-needed

#39 Refs 47: db:add preliminar entity relationship diagram
  docs/architecture.md
  docs/db-model.puml
  mk/plantuml.mk
Labels: no-qe-needed

#53 Fixes 128: build a container image on each pr
  .github/workflows/container-push-pr.yml
Labels: qe-testing-required

#45 Fixes 95: preset arches and versions
  api/docs.go
  api/openapi.json
  pkg/api/repository_parameters.go
  pkg/config/value_constraints.go
  pkg/dao/repository_test.go
  pkg/dao/suite_test.go
  pkg/handler/api.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_test.go
  pkg/models/base.go
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
  pkg/models/suite_test.go
  pkg/seeds/seeds.go
  pkg/seeds/suite_test.go
Labels: qe-testing-required

#38 Fixes 90: commands to download and load external repos
  build/Dockerfile
  cmd/dbmigrate/main.go
  cmd/external-repos/main.go
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  deployments/deployment.yaml
  mk/includes.mk
  mk/meta-repos.mk
  mk/repos.mk
  pkg/dao/interfaces.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/external_repos/external_repos.json
  pkg/external_repos/image_builder.go
  pkg/external_repos/store.go
  pkg/external_repos/store_test.go
  pkg/external_repos/suite_test.go
  pkg/handler/repository_test.go
  pkg/models/repository.go
Labels: no-qe-needed

#52 Fixes 127: fix version filter using group clause
  go.mod
  go.sum
  pkg/config/config.go
  pkg/dao/main_test.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/dao/suite_test.go
  pkg/db/db.go
  pkg/handler/repository_test.go
  pkg/models/base.go
  pkg/models/suite_test.go
  pkg/seeds/seeds.go
  pkg/seeds/suite_test.go
Labels: qe-testing-required

#50 Fixes 96: Add bulk create
  api/docs.go
  api/openapi.json
  pkg/api/repository.go
  pkg/dao/error.go
  pkg/dao/interfaces.go
  pkg/dao/repository.go
  pkg/dao/repository_test.go
  pkg/handler/repositories.go
  pkg/handler/repository_test.go
Labels: qe-testing-required

#57 Fixes 140: Create LICENSE
  LICENSE
Labels: qe-testing-required

#51 Fixes 103: add search for packages
  api/docs.go
  api/openapi.json
  pkg/api/repository_rpm.go
  pkg/dao/interfaces.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/handler/api.go
  pkg/handler/repository_rpm.go
  pkg/models/repository.go
  pkg/models/rpm.go
  pkg/seeds/seeds.go
Labels: qe-testing-required

#47 Refs 105: Add pr_checks and build_deploy
  build_deploy.sh
  mk/docker.mk
  pr_checks.sh
Labels: enhancement, no-qe-needed

#58 Refs 105: update clowdapp IMAGE
  deployments/deployment.yaml
Labels: no-qe-needed

#61 Refs 105: Rename pr_checks
  pr_check.sh
Labels: bug, no-qe-needed

#62 Refs 105: Update clowdapp name
  deployments/deployment.yaml
  pr_check.sh
Labels: bug, no-qe-needed

#55 Fixes 49: add introspection command
  cmd/external-repos/main.go
  configs/config.yaml.example
  go.mod
  go.sum
  pkg/config/config.go
  pkg/dao/interfaces.go
  pkg/dao/public_repositories.go
  pkg/dao/public_repositories_test.go
  pkg/dao/repository.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/ca.pem
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
  pkg/external_repos/store.go
  pkg/external_repos/store_test.go
  pkg/external_repos/suite_test.go
  pkg/external_repos/test_files/test_repomd.xml
  pkg/handler/api.go
  pkg/handler/repository_rpm.go
  pkg/models/repository.go
  pkg/seeds/seeds.go
Labels: no-qe-needed
