Repository content-services/content-sources-backend, pull requests merged in 2022-11, with the labels that each got.

#125 Fixes 233: update to go 1.18
  .github/workflows/content-sources-actions.yml
  build/Dockerfile
  go.mod
  go.sum
  mk/docker.mk
  pkg/dao/rpm_test.go
Labels: no-qe-needed

#134 Fixes 256: do not fail on errored introspection
  cmd/external-repos/main.go
  pkg/external_repos/introspect.go
Labels: no-qe-needed

#136 Fixes 264: fix TestValidateMessage unit test
  pkg/event/schema/schemas_test.go
Labels: qe-testing-needed

#138 Refs 264: Fix one missed case in the unit test
  pkg/event/schema/schemas_test.go
Labels: no-qe-needed

#140 Fixes 209: update base container image
  build/Dockerfile
Labels: no-qe-needed

#135 Fixes 255: update rpm search by matching substrings
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
Labels: qe-testing-needed, Ready for QE

#139 Fixes 262: ignore metalinks in external repos download
  cmd/external-repos/main.go
  pkg/external_repos/external_repos.json
  pkg/external_repos/image_builder.go
Labels: no-qe-needed

#133 Fixes 235: add /ping for kafka consumer
  build/Dockerfile
  cmd/content-sources/main.go
  cmd/kafka-introspect/main.go
  deployments/deployment.yaml
  mk/go-rules.mk
  pkg/config/config.go
  pkg/event/consumer.go
  pkg/event/consumer_test.go
  pkg/event/factory.go
  pkg/handler/api.go
  pkg/handler/api_test.go
Labels: no-qe-needed

#143 Refs 262: add rhel 8.7 repos
  pkg/external_repos/external_repos.json
  pkg/external_repos/image_builder.go
  pkg/external_repos/image_builder_test.go
Labels: no-qe-needed

#146 Refs 283: only select api pods for backend service
  deployments/deployment.yaml
Labels: qe-testing-needed

#147 Fixes 235: add /ping for kafka consumer (#133)
  build/Dockerfile
  cmd/content-sources/main.go
  cmd/kafka-introspect/main.go
  deployments/deployment.yaml
  mk/go-rules.mk
  pkg/config/config.go
  pkg/event/consumer.go
  pkg/event/consumer_test.go
  pkg/event/factory.go
  pkg/handler/api.go
  pkg/handler/api_test.go
Labels: no-qe-needed

#126 Fixes 182: change api errors to error objects
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/repository_parameters.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/value_constraints.go
  pkg/dao/external_resource.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/errors/dao_error.go
  pkg/errors/dao_error_test.go
  pkg/errors/handler_error.go
  pkg/errors/handler_error_test.go
  pkg/external_repos/introspect.go
  pkg/handler/api.go
  pkg/handler/api_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_rpm.go
  pkg/test/mocks/repositories.go
Labels: qe-testing-needed, Ready for QE

#144 Fixes 266: use gorm config for batch creation
  pkg/config/config.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/db/db.go
  pkg/external_repos/introspect.go
  pkg/handler/api.go
Labels: qe-testing-needed, Ready for QE
