Repository content-services/content-sources-backend, pull requests merged in 2022-10, with the labels that each got.

#118 Fixes 187: speed up seeds_test
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
Labels: no-qe-needed

#104 Fixes 152: Smarter introspection job
  cmd/external-repos/main.go
  deployments/deployment.yaml
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
Labels: qe-testing-needed, Ready for QE

#120 Fixes 202: Log info and debug requests
  pkg/config/config.go
Labels: no-qe-needed

#119 Fixes 186: Refactor test suites to run individual test files
  pkg/config/config.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_config_test.go
  pkg/dao/rpm_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/store_test.go
  pkg/external_repos/suite_test.go
  pkg/models/repository_configuration_test.go
  pkg/models/repository_rpm_test.go
  pkg/models/repository_test.go
  pkg/models/rpm_test.go
  pkg/models/suite_test.go
  pkg/seeds/seeds_test.go
  pkg/seeds/suite_test.go
Labels: no-qe-needed

#114 Refs 183: Add iqe marker expression
  pr_check.sh
Labels: no-qe-needed

#115 Fixes 194: Update with zero values in repository dao
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
Labels: no-qe-needed

#112 Fixes 76: Add fetchGpgKey API
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/api/repository_parameters.go
  pkg/dao/external_resource.go
  pkg/dao/external_resource_test.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config_test.go
  pkg/handler/api.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/test/mocks/external_resources.go
  pkg/test/mocks/repositories.go
Labels: qe-testing-needed, Ready for QE

#116 Fixes 189: use gpg key in validation step
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/api/repository_parameters.go
  pkg/dao/external_resource.go
  pkg/dao/external_resource_test.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/test/gpg.go
  pkg/test/gpg/gpgkey.pub
  pkg/test/gpg/repomd.xml
  pkg/test/gpg/repomd.xml.asc
  pkg/test/mocks/external_resources.go
Labels: qe-testing-needed, Ready for QE

#123 Fixes 227: package_count=0 after introspect
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
Labels: no-qe-needed

#121 Fixes 203: Add URL trailing slash on creation
  pkg/dao/external_resource.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/models/repository.go
  pkg/models/repository_test.go
Labels: qe-testing-needed, Ready for QE

#127 Fixes 207: return 404 when uuid syntax invalid
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
Labels: qe-testing-needed, Ready for QE

#122 Fixes 180: add name and url repo filters
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/dao/repository_config.go
  pkg/dao/repository_config_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
Labels: qe-testing-needed, Ready for QE

#129 Fixes 245: add trailing slash on introspect if needed
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#128 Fixes 205: Return error as last item
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
Labels: no-qe-needed

#124 Fixes 212: Add sort/search to rpm List
  api/docs.go
  api/openapi.json
  pkg/api/repository_rpm.go
  pkg/dao/helpers.go
  pkg/dao/helpers_test.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config.go
  pkg/dao/rpm.go
  pkg/dao/rpm_test.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/handler/repositories.go
  pkg/handler/repository_rpm.go
Labels: qe-testing-needed

#131 Fixes 242: set minReplicas to 3
  deployments/deployment.yaml
Labels: no-qe-needed

#113 Fixes 151: introspect repo from kafka message
  .dockerignore
  .gitignore
  .golangci.yaml
  .vscode/launch.json
  README.md
  cmd/kafka-introspect/main.go
  configs/config.yaml.example
  deployments/deployment.yaml
  go.mod
  go.sum
  kafka/Dockerfile
  mk/gen-event-messages.mk
  mk/go-rules.mk
  mk/includes.mk
  mk/kafka.mk
  mk/variables.mk
  pkg/config/config.go
  pkg/config/event.go
  pkg/config/event_test.go
  pkg/dao/repository_config.go
  pkg/event/README.md
  pkg/event/adapter/introspect.go
  pkg/event/adapter/introspect_test.go
  pkg/event/adapter/kafka.go
  pkg/event/adapter/kafka_test.go
  pkg/event/config.go
  pkg/event/consumer.go
  pkg/event/consumer_test.go
  pkg/event/factory.go
  pkg/event/handler/introspect.go
  pkg/event/handler/introspect_test.go
  pkg/event/interface.go
  pkg/event/message/.keepme
  pkg/event/message/headers.go
  pkg/event/message/introspect_request.types.gen.go
  pkg/event/producer/helper_test.go
  pkg/event/producer/introspect_request.go
  pkg/event/producer/introspect_request_test.go
  pkg/event/producer/producer.go
  pkg/event/producer/producer_test.go
  pkg/event/schema/README.md
  pkg/event/schema/introspectRequest.message.json
  pkg/event/schema/introspectRequest.message.yaml
  pkg/event/schema/schemas.go
  pkg/event/schema/schemas_test.go
  pkg/event/topics.go
  pkg/event/topics_test.go
  pkg/event/utils.go
  pkg/event/utils_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/utils.go
  scripts/kafka-print-last-version.py
  test/kafka/demo-introspect-request-1.json
  test/kafka/demo-introspect-request-2.json
Labels: qe-testing-needed, Ready for QE
