Repository content-services/content-sources-backend, pull requests merged in 2023-12, with the labels that each got.

#445 Fixes 2282: reduce number of introspect tasks
  cmd/external-repos/main.go
  pkg/cache/cache_mock.go
  pkg/config/value_constraints.go
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repositories_mock.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/snapshots_mock.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#493 Fixes 3215: Add module_hotfixes flag for repositories
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20231201193045_add_module_hotfixes_to_repository_configs.down.sql
  db/migrations/20231201193045_add_module_hotfixes_to_repository_configs.up.sql
  pkg/api/repositories.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/handler/repositories_test.go
  pkg/models/repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#461 Fixes 2443: API support for list / search package groups
  api/docs.go
  api/openapi.json
  db/migrations/20231031150317_create_package_groups_table.down.sql
  db/migrations/20231031150317_create_package_groups_table.up.sql
  docs/db-model.puml
  pkg/api/repository_package_groups.go
  pkg/dao/interfaces.go
  pkg/dao/package_groups.go
  pkg/dao/package_groups_mock.go
  pkg/dao/package_groups_test.go
  pkg/dao/registry_mock.go
  pkg/dao/repositories_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/external_repos/test_files/comps.xml
  pkg/external_repos/test_files/repomd.xml
  pkg/handler/api.go
  pkg/handler/repository_package_groups.go
  pkg/handler/repository_package_groups_test.go
  pkg/models/package_group.go
  pkg/models/package_group_test.go
  pkg/models/repository.go
  pkg/models/repository_package_group.go
  pkg/models/repository_package_group_test.go
  pkg/models/suite_test.go
Labels: qe-testing-needed, Ready for QE

#495 Refs 2443: fix db migration
  db/migrations.latest
  db/migrations/20231205092913_create_package_groups_table.down.sql
  db/migrations/20231205092913_create_package_groups_table.up.sql
Labels: qe-testing-needed

#491 Fixes 3189: change gpg key file endpoint
  api/docs.go
  api/openapi.json
  deployments/deployment.yaml
  pkg/dao/snapshots.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/middleware/enforce_identity.go
Labels: qe-testing-needed, Ready for QE

#501 Fixes 3271: remove redundant lint CI tests
  .github/workflows/content-sources-actions.yml
Labels: no-qe-needed

#497 Fixes 3250: provide filter for excluding loaded RH repos
  .rhcicd/pr_check.sh
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/external_repos/redhat_repos.go
  pkg/external_repos/redhat_repos.json
Labels: qe-testing-needed, Ready for QE

#498 Fixes 3037: Adds a url validity check.
  pkg/dao/repository_configs_test.go
  pkg/models/repository.go
Labels: qe-testing-needed, Ready for QE

#499 Fixes 3016: Reject requests with org id of -1
  pkg/config/config.go
  pkg/middleware/enforce_identity.go
  pkg/middleware/enforce_identity_test.go
  pkg/middleware/enforce_json.go
  pkg/router/route.go
Labels: qe-testing-needed, Ready for QE

#503 Refs 3016: revert org id check
  pkg/config/config.go
  pkg/middleware/enforce_identity.go
  pkg/middleware/enforce_identity_test.go
  pkg/middleware/enforce_json.go
  pkg/router/route.go
Labels: qe-testing-needed

#504 Fixes 3016: Reject requests with org id of -1
  pkg/config/config.go
  pkg/middleware/enforce_identity.go
  pkg/middleware/enforce_identity_test.go
  pkg/middleware/enforce_json.go
  pkg/router/route.go
Labels: qe-testing-needed, Ready for QE

#507 Refs 3016: fix order of middleware for metrics endpoint
  pkg/router/route.go
Labels: qe-testing-needed

#486 Fixes 2969: fetch (POST) snapshots for content_templates
  api/docs.go
  api/openapi.json
  pkg/api/snapshots.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/pulp_client/pulp_client_mock.go
Labels: qe-testing-needed, Ready for QE

#512 Fixes 1973: Prevents snapshots on non-snapshot enabled repos
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed

#513 Fixes 1973: Typo in model
  api/docs.go
  api/openapi.json
  pkg/api/snapshots.go
Labels: qe-testing-needed, Ready for QE
