Repository content-services/content-sources-backend, pull requests merged in 2023-09, with the labels that each got.

#380 Refs 2486: trigger a manual build
  build/.manual_trigger
Labels: qe-testing-needed

#375 Fixes 2018: add task cleanup
  cmd/external-repos/main.go
  pkg/dao/interfaces.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/external_repos/introspect.go
Labels: qe-testing-needed, Ready for QE

#389 Refs 1963: Bump mem request to 200Mi
  deployments/deployment.yaml
Labels: qe-testing-needed, Ready for QE

#385 Fixes 2543: use a null uuid for bad uuids
  pkg/dao/admin_tasks.go
  pkg/dao/helpers.go
  pkg/dao/repository_configs.go
  pkg/dao/rpms.go
  pkg/dao/snapshots.go
  pkg/dao/task_info.go
Labels: no-qe-needed

#394 Refs 2631: debug s3 connection
  pkg/config/config.go
Labels: qe-testing-needed

#383 Fixes 2319: add repo filtering by origin & type
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20230831162419_add_repo_fields.down.sql
  db/migrations/20230831162419_add_repo_fields.up.sql
  pkg/api/api.go
  pkg/api/repositories.go
  pkg/config/config.go
  pkg/config/value_constraints.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/handler/api.go
  pkg/handler/features_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/repository.go
  pkg/seeds/seeds.go
Labels: qe-testing-needed, Ready for QE

#395 Fixes 2631: handle bucket hostname with proto
  pkg/config/config.go
  pkg/config/config_test.go
Labels: qe-testing-needed

#390 Fixes 2264: remove kafka based inspection
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  configs/config.yaml.example
  go.mod
  go.sum
  mk/gen-event-messages.mk
  mk/go-rules.mk
  mk/includes.mk
  pkg/config/config.go
  pkg/config/event.go
  pkg/event/README.md
  pkg/event/adapter/introspect.go
  pkg/event/adapter/introspect_test.go
  pkg/event/adapter/kafka.go
  pkg/event/adapter/kafka_test.go
  pkg/event/consumer.go
  pkg/event/consumer_test.go
  pkg/event/factory.go
  pkg/event/handler/introspect.go
  pkg/event/handler/introspect_test.go
  pkg/event/interface.go
  pkg/event/message/.keepme
  pkg/event/message/headers.go
  pkg/event/message/introspect_request.types.gen.go
  pkg/event/producer/helper_test.go
  pkg/event/producer/introspect_request.go
  pkg/event/producer/introspect_request_test.go
  pkg/event/producer/producer.go
  pkg/event/producer/producer_test.go
  pkg/event/schema/README.md
  pkg/event/schema/introspectRequest.message.json
  pkg/event/schema/introspectRequest.message.yaml
  pkg/event/schema/schemas.go
  pkg/event/schema/schemas_test.go
  pkg/event/topics.go
  pkg/event/topics_test.go
  pkg/event/utils.go
  pkg/event/utils_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: no-qe-needed

#406 Fixes 2668: use newer yummy
  go.mod
  go.sum
Labels: qe-testing-needed, Ready for QE

#387 Fixes 1963: nightly sync
  .gitignore
  cmd/external-repos/main.go
  cmd/test/main.go.bak
  cmd/test/main.go.listupstreampulps
  cmd/test/main.go.multirequest
  create.http
  deployments/deployment.yaml
  hammer.py
  my-postgres.conf
  pkg/config/config.go
  pkg/config/value_constraints.go
  pkg/dao/admin_tasks_test.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info_test.go
  pkg/external_repos/introspect.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
  scripts/header_org_admin.sh
  update.http
Labels: qe-testing-needed, Ready for QE

#397 Fixes 2381: specify if name or URL is duplicated
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE
