Repository content-services/content-sources-backend, pull requests merged in 2023-07, with the labels that each got.

#326 Fixes 2065: conditional Introspect & fixed update
  pkg/dao/repository_configs.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
Labels: no-qe-needed

#330 Fixes 2065: Fix potential empty notification
  pkg/notifications/client.go
Labels: no-qe-needed

#315 Fixes 1579: update url on remote if url changed
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/api.go
  pkg/handler/api_test.go
  pkg/handler/features.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/snapshot_model.go
  pkg/models/snapshot_model_test.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/status.go
  pkg/seeds/seeds.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#325 Fixes 326: Add repository bulk delete API
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#316 Fixes 1868: Admin Task API
  cmd/external-repos/main.go
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/api/admin_task.go
  pkg/api/api.go
  pkg/config/config.go
  pkg/dao/admin_tasks.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/admin_tasks_test.go
  pkg/dao/interfaces.go
  pkg/dao/registry_mock.go
  pkg/handler/admin_tasks.go
  pkg/handler/admin_tasks_test.go
  pkg/handler/api.go
  pkg/handler/features.go
  pkg/handler/features_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/task_info.go
  pkg/seeds/seeds.go
  pkg/tasks/introspect.go
  pkg/tasks/payloads/repository_introspect.go
  pkg/tasks/payloads/repository_snapshot.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed

#332 Fixes 2112: RPM fetch 404
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/repository_rpms.go
  pkg/handler/repository_rpms_test.go
Labels: qe-testing-needed, Ready for QE

#327 Refs 1882: retry refresh heartbeat when no rows affected
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/worker/worker_pool.go
Labels: no-qe-needed

#337 Fixes 2183: fix deadlock in concurrent task enqueue
  pkg/config/config.go
  pkg/db/db.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/pgx_pool_wrapper.go
Labels: qe-testing-needed, Ready for QE
