Repository content-services/content-sources-backend, pull requests merged in 2023-08, with the labels that each got.

#333 Fixes 1846: log request ID
  cmd/external-repos/main.go
  db/migrations/20230706145024_add_request_id_to_tasks.down.sql
  db/migrations/20230706145024_add_request_id_to_tasks.up.sql
  pkg/config/logging.go
  pkg/dao/interfaces.go
  pkg/event/handler/introspect.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/middleware/rbac.go
  pkg/models/task_info.go
  pkg/pulp_client/client.go
  pkg/pulp_client/task.go
  pkg/rbac/client_wrapper.go
  pkg/router/route.go
  pkg/tasks/client/client.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  pkg/tasks/worker/worker.go
  pkg/tasks/worker/worker_pool_test.go
  test/integration/snapshot_test.go
Labels: no-qe-needed

#341 Fixes 2193: popular repository pagination
  api/docs.go
  api/openapi.json
  pkg/handler/popular_repositories.go
  pkg/handler/popular_repositories_test.go
Labels: qe-testing-needed, Ready for QE

#339 Fixes 2224: admin task fetch 404
  pkg/dao/admin_tasks.go
  pkg/dao/admin_tasks_test.go
Labels: no-qe-needed

#345 Refs 1947: Adjust memory request and limit, hms-integration
  deployments/testing-integration.yaml
Labels: bug, no-qe-needed

#350 Fixes 2270: prevent out of order migrations
  cmd/dbmigrate/main.go
  db/migrations.latest
  pkg/db/db.go
Labels: no-qe-needed

#340 Fixes 2244,2280: simplify snap model and soft del repo_conf
  .github/workflows/title.yml
  db/migrations.latest
  db/migrations/20230807161216_refactor_snapshots.down.sql
  db/migrations/20230807161216_refactor_snapshots.up.sql
  pkg/dao/domain_dao_mock.go
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/db/db.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/repository_configuration.go
  pkg/models/repository_configuration_test.go
  pkg/models/snapshot_model.go
  pkg/models/snapshot_model_test.go
  pkg/seeds/seeds.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
Labels: no-qe-needed

#353 Fixes 2310: fix 404 err on delete task
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  test/integration/delete_test.go
Labels: no-qe-needed

#351 Fixes 2273: handle bad uuids on validate api
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/handler/repository_parameters.go
Labels: qe-testing-needed, Ready for QE

#355 Fixes 2315: set proper s3 acl and update domains
  cmd/content-sources/main.go
  pkg/pulp_client/domains.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
Labels: no-qe-needed

#338 Fixes 2083: log when a task fails to complete
  pkg/tasks/worker/worker.go
Labels: no-qe-needed

#357 Refs 645: specifying runAsNonRoot for deploy
  deployments/deployment.yaml
Labels: no-qe-needed

#343 Fixes 1965: configurable download policies in pulp
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/pulp_client/rpm_remote.go
Labels: no-qe-needed

#363 Fixes 2367: talk to pulp api directly
  deployments/deployment.yaml
Labels: qe-testing-needed, Ready for QE

#359 Fixes 1971: Task info list filtering and new fields
  api/docs.go
  api/openapi.json
  pkg/api/task_info.go
  pkg/dao/interfaces.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/handler/task_info.go
  pkg/handler/task_info_test.go
  pkg/models/task_info.go
  pkg/seeds/seeds.go
Labels: qe-testing-needed, Ready for QE

#365 Fixes 2239: fix various 500 errors caused by bad params
  pkg/dao/admin_tasks.go
  pkg/dao/repository_configs.go
  pkg/dao/rpms.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
  pkg/handler/snapshots.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#374 Refs 645: move securityContext
  deployments/deployment.yaml
Labels: no-qe-needed

#377 Fixes 2419: ignore rbac check for org admins
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/rbac/client_wrapper.go
  pkg/rbac/client_wrapper_test.go
Labels: no-qe-needed
