Repository content-services/content-sources-backend, pull requests merged in 2023-06, with the labels that each got.

#279 Fixes 1471: Integrate snapshot task into application
  api/docs.go
  api/openapi.json
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  deployments/deployment.yaml
  mk/pulp.mk
  mk/variables.mk
  pkg/api/repositories.go
  pkg/config/config.go
  pkg/config/logging.go
  pkg/dao/interfaces.go
  pkg/dao/repository_config_mock.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/external_repos/pulp_external_repos/pulp.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/models/repository_configuration.go
  pkg/pulp_client/client.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/mock_pulp_client.go
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_publication.go
  pkg/pulp_client/rpm_remote.go
  pkg/pulp_client/rpm_repositories.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/pulp_client/task.go
  pkg/tasks/queue/mock_queue.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#299 Fixes 1470: switch nightly introspect to tasking system
  cmd/external-repos/main.go
  deployments/deployment.yaml
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/tasks/introspect.go
Labels: no-qe-needed

#303 Fixes 602: Update schema output and dataSchema typo
  pkg/notifications/client.go
  pkg/notifications/client_test.go
Labels: no-qe-needed

#300 Fixes 1644: Enforce JSON Content Type
  api/docs.go
  api/openapi.json
  pkg/handler/repositories.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_rpms.go
  pkg/middleware/enforce_json.go
  pkg/middleware/enforce_json_test.go
  pkg/router/route.go
Labels: qe-testing-needed, Ready for QE

#296 Fixes 1580: Add API to list and fetch tasks
  api/docs.go
  api/openapi.json
  pkg/api/task_info.go
  pkg/dao/interfaces.go
  pkg/dao/registry_mock.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/handler/api.go
  pkg/handler/task_info.go
  pkg/handler/task_info_test.go
  pkg/middleware/rbac_map.go
  pkg/models/task_info.go
  pkg/models/task_info_test.go
  pkg/router/route_test.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/mock_queue.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/queue.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  pkg/tasks/worker/worker.go
  pkg/tasks/worker/worker_pool.go
Labels: qe-testing-needed, Ready for QE

#278 Fixes 1865: fix repository list filters
  pkg/dao/repository_configs.go
Labels: qe-testing-needed, Ready for QE

#306 Fixes 25: Remove selenium container from testing.yaml
  deployments/testing.yaml
Labels: qe-testing-needed

#304 Fixes 1486: set rbac perms at route definition
  go.mod
  go.sum
  pkg/client/doc.go
  pkg/handler/popular_repositories.go
  pkg/handler/repositories.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_rpms.go
  pkg/handler/task_info.go
  pkg/handler/utils.go
  pkg/middleware/rbac.go
  pkg/middleware/rbac_map.go
  pkg/middleware/rbac_test.go
  pkg/rbac/client_wrapper.go
  pkg/rbac/client_wrapper_test.go
  pkg/rbac/mock_client_wrapper.go
  pkg/rbac/permission_map.go
  pkg/rbac/permission_map_test.go
  pkg/router/route.go
  pkg/test/mocks/client/rbac.go
Labels: no-qe-needed

#307 Fixes 1924: move notifications loading to startup
  cmd/content-sources/main.go
  pkg/config/config.go
Labels: no-qe-needed

#313 Fixes 1989: set debug for ephemeral
  deployments/deployment.yaml
Labels: qe-testing-needed

#308 Fixes 1501: add API to list snapshots
  api/docs.go
  api/openapi.json
  pkg/api/repositories.go
  pkg/api/snapshots.go
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/api.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/router/route_test.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#319 Fixes 2019: update arch and db docs
  README.md
  docs/architecture.md
  docs/architecture.png
  docs/architecture.puml
  docs/architecture.svg
  docs/db-model.puml
  docs/db-model.svg
  mk/plantuml.mk
Labels: qe-testing-needed

#309 Fixes 1624: adds config/api detailing features
  api/docs.go
  api/openapi.json
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/api/features.go
  pkg/config/config.go
  pkg/handler/api.go
  pkg/handler/features.go
  pkg/handler/features_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/router/route_test.go
  scripts/header.sh
Labels: qe-testing-needed, Ready for QE

#314 Fixes 1469: delete snapshots when deleting repo config
  cmd/content-sources/main.go
  docs/pkg-graph.svg
  pkg/config/tasks.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/middleware/rbac.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_repositories.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/tasks/client/client.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/worker/worker.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#311 Fixes 1948: Add introspection/edit/delete notifications
  go.mod
  go.sum
  pkg/config/config.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/external_repos/introspect.go
  pkg/handler/repositories.go
  pkg/notifications/client.go
Labels: no-qe-needed

#322 Fixes 1882: only refresh running tasks
  pkg/tasks/worker/worker.go
  pkg/tasks/worker/worker_pool_test.go
Labels: no-qe-needed

#324 Fixes 2058: Empty url on introspect notification
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: no-qe-needed
