Repository content-services/content-sources-backend, pull requests merged in 2023-01, with the labels that each got.

#154 Fixes 280: switch to using repomd checksum
  db/migrations/20221130134116_move_revision_to_checksum.down.sql
  db/migrations/20221130134116_move_revision_to_checksum.up.sql
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/models/repository.go
Labels: qe-testing-needed, Ready for QE

#160 Refs 269: add more arch detail to docs
  docs/architecture.md
  docs/architecture.puml
  docs/architecture.svg
  docs/db-model.puml
  docs/db-model.svg
Labels: no-qe-needed

#156 Refs 280: remove revision column
  db/migrations/20221212134912_remove_revision.down.sql
  db/migrations/20221212134912_remove_revision.up.sql
Labels: qe-testing-needed

#162 Fixes 319: Order Arch list alphabetically
  pkg/config/value_constraints.go
  pkg/handler/repository_rpms_test.go
Labels: qe-testing-needed, Ready for QE

#161 Fixes 299: add cloudwatch support
  .github/workflows/content-sources-actions.yml
  configs/config.yaml.example
  go.mod
  go.sum
  mk/lint.mk
  pkg/config/config.go
  pkg/config/logging.go
Labels: no-qe-needed

#165 Refs 322: Add clowdjobinvocation template for stage testing
  deployments/testing.yaml
Labels: qe-testing-needed

#172 Refs 322: Change CJI env to stage_proxy
  deployments/testing.yaml
Labels: qe-testing-needed

#174 Refs 322: back to stage_post_deploy
  deployments/testing.yaml
Labels: qe-testing-needed

#169 Fixes 298: add test for listRepositoryRpms handler
  pkg/handler/repository_rpms_test.go
Labels: no-qe-needed

#151 Fixes 267: Add a metrics endpoint
  .gitignore
  .vscode/launch.json
  README.md
  cmd/content-sources/main.go
  configs/config.yaml.example
  configs/prometheus.example.yaml
  deployments/deployment.yaml
  go.mod
  go.sum
  mk/docker.mk
  mk/go-rules.mk
  mk/includes.mk
  mk/kafka.mk
  mk/meta-prometheus.mk
  mk/prometheus.mk
  mk/variables.mk
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/dao/interfaces.go
  pkg/dao/metrics.go
  pkg/dao/metrics_test.go
  pkg/dao/suite_test.go
  pkg/handler/utils/path.go
  pkg/handler/utils/path_test.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/custom/collector_test.go
  pkg/instrumentation/metrics.go
  pkg/instrumentation/metrics_test.go
  pkg/instrumentation/middleware.go
  pkg/instrumentation/middleware_test.go
Labels: qe-testing-needed, Ready for QE

#164 Refs 328: change dev pgsql container name & port
  configs/config.yaml.example
  mk/db.mk
  mk/variables.mk
Labels: no-qe-needed

#170 Fixes 326: Filter repositories by status
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/seeds/seeds.go
  pkg/seeds/seeds_test.go
Labels: qe-testing-needed, Ready for QE

#178 Fixes 337: stop logging ping & metrics
  pkg/config/config.go
  pkg/config/logging.go
Labels: no-qe-needed

#182 Refs 268: make grafana datasources env variable
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: qe-testing-needed

#175 Fixes 540: Add docker compose
  .gitignore
  README.md
  compose_files/kafka/Dockerfile
  compose_files/kafka/config/server.properties
  compose_files/kafka/config/zookeeper.properties
  compose_files/kafka/scripts/kafka-entrypoint.sh
  compose_files/kafka/scripts/kafka-print-last-version.py
  compose_files/kafka/scripts/zookeeper-entrypoint.sh
  compose_files/kafka/scripts/zookeeper-healthcheck.sh
  compose_files/pulp/.gitignore
  deployments/docker-compose.yml
  mk/compose.mk
  mk/db.mk
  mk/docker.mk
  mk/includes.mk
  mk/kafka.mk
  mk/meta-compose.mk
  mk/pulp.mk
  mk/variables.mk
Labels: no-qe-needed

#186 Fixes 1117: use newer yummy for hashicorp repos
  go.mod
  go.sum
Labels: qe-testing-needed

#185 Fixes 1118: cleanup url before bulkcreate
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE

#184 Fixes 377: Remove unused makefile vars
  mk/docker.mk
Labels: no-qe-needed

#187 Fixes 1138: use env variable for count grafana panels
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: qe-testing-needed
