Repository content-services/content-sources-backend, pull requests merged in 2023-05, with the labels that each got.

#261 Fixes 1672: support multiple gpg keys
  pkg/dao/repository_configs.go
  pkg/test/gpg/gpgkey.pub
  pkg/test/gpg/repomd.xml
  pkg/test/gpg/repomd.xml.asc
Labels: qe-testing-needed, Ready for QE

#248 Fixes 1468: add repo snapshot task
  .github/workflows/content-sources-actions.yml
  cmd/external-repos/main.go
  configs/config.yaml.example
  db/migrations/20230330144631_snapshotting_custom.down.sql
  db/migrations/20230330144631_snapshotting_custom.up.sql
  go.mod
  go.sum
  mk/go-rules.mk
  mk/variables.mk
  pkg/config/config.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/registry_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_config_mock.go
  pkg/dao/repository_configs.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshot_model.go
  pkg/dao/snapshot_model_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_mocks_test.go
  pkg/external_repos/introspect_test.go
  pkg/external_repos/pulp.go
  pkg/handler/api.go
  pkg/handler/popular_repositories.go
  pkg/handler/popular_repositories_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/repository_rpms.go
  pkg/handler/repository_rpms_test.go
  pkg/pulp_client/client.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/mock_pulp_client.go
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_publication.go
  pkg/pulp_client/rpm_remote.go
  pkg/pulp_client/rpm_repositories.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/pulp_client/task.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
  test/integration/snapshot_test.go
  test/integration/suite_test.go
Labels: no-qe-needed

#265 Fixes 1759: add 9.2 repos
  pkg/external_repos/external_repos.json
Labels: qe-testing-needed, Ready for QE

#267 Fixes 1759: add 9.2 repos
  pkg/external_repos/external_repos.json
Labels: qe-testing-needed

#264 Fixes 1735: add rbac caching w/ redis
  configs/config.yaml.example
  deployments/deployment.yaml
  deployments/docker-compose.yml
  go.mod
  go.sum
  pkg/cache/noop.go
  pkg/cache/rbac_cache.go
  pkg/cache/rbac_cache_mock.go
  pkg/cache/redis.go
  pkg/client/rbac.go
  pkg/client/rbac_test.go
  pkg/config/config.go
  pkg/middleware/rbac.go
  pkg/middleware/rbac_test.go
  pkg/test/mocks/client/rbac.go
Labels: no-qe-needed

#268 Refs 1770: add cert expiry metric
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/metrics.go
Labels: no-qe-needed

#269 Fixes 602: Send create notification
  deployments/deployment.yaml
  go.mod
  go.sum
  pkg/handler/repositories.go
  pkg/notifications/client.go
  pkg/notifications/eventNames.go
Labels: no-qe-needed

#273 Fixes 1693: update yummy to v1.0.5
  go.mod
  go.sum
Labels: qe-testing-needed, Ready for QE

#271 Refs 1468: fix compose up and pulp
  mk/pulp.mk
Labels: no-qe-needed

#275 Fixes 602: Fixes incorrect method type and error handling
  go.mod
  pkg/notifications/client.go
Labels: no-qe-needed

#280 Fixes 602: Fix defer close
  pkg/notifications/client.go
Labels: no-qe-needed

#284 Fixes 602: Add client to config
  pkg/config/config.go
  pkg/notifications/client.go
Labels: no-qe-needed

#288 Fixes 602: Add Logging
  pkg/config/config.go
  pkg/notifications/client.go
Labels: no-qe-needed

#289 Fixes 602: Add SSL configuration
  go.mod
  go.sum
  pkg/config/config.go
Labels: no-qe-needed

#290 Fixes 602: Add SSL/SASL authentication
  pkg/config/config.go
Labels: no-qe-needed

#291 Fixes 602: Update error to better return result
  pkg/notifications/client.go
Labels: no-qe-needed

#277 Refs 1471: tasking fixes
  cmd/content-sources/main.go
  configs/config.yaml.example
  pkg/config/config.go
  pkg/handler/api.go
  pkg/tasks/client/client.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/mock_queue.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/worker/worker.go
  pkg/tasks/worker/worker_pool.go
  pkg/tasks/worker/worker_pool_test.go
Labels: qe-testing-needed

#286 Fixes 1841: correct param validate mock
  pkg/dao/repository_config_mock.go
  pkg/handler/repository_parameters.go
  pkg/handler/repository_parameters_test.go
Labels: no-qe-needed

#297 Fixes 1845: fix TearDownTest capitalization
  pkg/client/rbac_test.go
Labels: no-qe-needed

#298 Refs 1470: turn on new tasking system in stage
  deployments/deployment.yaml
Labels: no-qe-needed
