Repository content-services/content-sources-backend, pull requests merged in 2023-10, with the labels that each got.

#402 Fixes 2490: make migrations idempotent
  .github/workflows/content-sources-actions.yml
  db/migrations/20220512132042_create_repository_configurations_table.up.sql
  db/migrations/20220923124812_add_package_count.down.sql
  db/migrations/20220923124812_add_package_count.up.sql
  db/migrations/20221130134116_move_revision_to_checksum.down.sql
  db/migrations/20221130134116_move_revision_to_checksum.up.sql
  db/migrations/20221212134912_remove_revision.down.sql
  db/migrations/20221212134912_remove_revision.up.sql
  db/migrations/20230322110439_add_failed_introspection_count_to_repositories.down.sql
  db/migrations/20230322110439_add_failed_introspection_count_to_repositories.up.sql
  db/migrations/20230330144631_snapshotting_custom.down.sql
  db/migrations/20230330144631_snapshotting_custom.up.sql
  db/migrations/20230410105610_add_jobqueue.down.sql
  db/migrations/20230410105610_add_jobqueue.up.sql
  db/migrations/20230706145024_add_request_id_to_tasks.down.sql
  db/migrations/20230706145024_add_request_id_to_tasks.up.sql
  db/migrations/20230707065625_add_repository_path.down.sql
  db/migrations/20230707065625_add_repository_path.up.sql
  db/migrations/20230804092757_add_domains.up.sql
  db/migrations/20230807161216_refactor_snapshots.up.sql
  db/migrations/20230814125610_add_snapshot_added_removed.down.sql
  db/migrations/20230814125610_add_snapshot_added_removed.up.sql
  db/migrations/20230823115016_add_last_snapshot_task.down.sql
  db/migrations/20230823115016_add_last_snapshot_task.up.sql
  db/migrations/20230831162419_add_repo_fields.down.sql
  db/migrations/20230831162419_add_repo_fields.up.sql
  mk/go-rules.mk
Labels: no-qe-needed

#415 Refs 1581: debug register listener
  pkg/tasks/queue/pgqueue.go
Labels: qe-testing-needed

#417 Refs 1581: cancel task with cause
  pkg/tasks/introspect.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/worker/worker.go
Labels: qe-testing-needed

#418 Fixes 2588: Existing popular repositories not found error
  .gitignore
  pkg/dao/repository_configs_test.go
  pkg/handler/popular_repositories.go
  pkg/handler/popular_repositories_test.go
Labels: qe-testing-needed, Ready for QE

#407 Fixes 2245: add red hat repo for nightly snapshotting
  cmd/external-repos/main.go
  create.http
  deployments/docker-compose.yml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/value_constraints.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/external_repos/redhat.gpg
  pkg/external_repos/redhat_repos.go
  pkg/external_repos/redhat_repos.json
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/rpm_remote.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#416 Fixes 2717: add config to turn off notifs
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/notifications/client.go
Labels: qe-testing-needed, Ready for QE

#427 Fixes 2777: removed duplicate key from config example
  configs/config.yaml.example
Labels: qe-testing-needed, Ready for QE

#429 Fixes 2776: set max pg pool for task db
  pkg/tasks/queue/pgqueue.go
Labels: qe-testing-needed, Ready for QE

#419 Fixes 2582,2425: add account_id to task table, trim error
  cmd/external-repos/main.go
  db/migrations.latest
  db/migrations/20231005134337_add_account_id_to_tasks.down.sql
  db/migrations/20231005134337_add_account_id_to_tasks.up.sql
  db/migrations/20231006121354_longer_task_errors.down.sql
  db/migrations/20231006121354_longer_task_errors.up.sql
  pkg/dao/admin_tasks.go
  pkg/dao/admin_tasks_test.go
  pkg/handler/repositories.go
  pkg/models/task_info.go
  pkg/seeds/seeds.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
Labels: qe-testing-needed, Ready for QE

#431 Refs 2425: trim error on update
  db/migrations/20231006121354_longer_task_errors.up.sql
Labels: qe-testing-needed

#414 Fixes 2615: add config.repo endpoint
  api/docs.go
  api/openapi.json
  cmd/test/main.go.bak
  cmd/test/main.go.listupstreampulps
  cmd/test/main.go.multirequest
  configs/config.yaml.example
  pkg/api/snapshots.go
  pkg/cache/cache.go
  pkg/cache/cache_mock.go
  pkg/cache/noop.go
  pkg/cache/rbac_cache_mock.go
  pkg/cache/redis.go
  pkg/config/config.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/popular_repositories.go
  pkg/handler/popular_repositories_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/models/snapshot.go
  pkg/models/snapshot_test.go
  pkg/pulp_client/client.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/status.go
  pkg/rbac/client_wrapper.go
  pkg/rbac/client_wrapper_test.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#432 Fixes 2832: trim introspection error
  pkg/dao/repositories_test.go
  pkg/models/base.go
  pkg/models/repository.go
Labels: qe-testing-needed, Ready for QE

#437 Refs 2361: Update integration-testing template parameters
  deployments/testing-integration.yaml
Labels: enhancement, qe-approved

#434 Refs 2615: don't propagate canceled context
  pkg/dao/repository_configs.go
  pkg/dao/snapshots.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed

#440 Fixes 2890: don't query pulp if not enabled
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE

#433 Fixes 2738: support SCRAM-SHA-512 sasl mech for kafka
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/event.go
  pkg/event/scram_client.go
Labels: qe-testing-needed, Ready for QE

#444 Fixes 2450: remove org admin skip setting
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/rbac/client_wrapper.go
  pkg/rbac/client_wrapper_test.go
  pkg/test/handler/utils.go
  scripts/header_org_admin.sh
Labels: no-qe-needed

#451 Fixes 2918: use parent context for cancel test
  pkg/tasks/queue/pgqueue_test.go
Labels: no-qe-needed

#453 Fixes 2926: Add RHEL 8.9 & 9.3 repos for introspection
  pkg/external_repos/external_repos.json
Labels: qe-testing-needed

#452 Refs 2675: rename kafka-consumer deployment
  deployments/deployment.yaml
Labels: no-qe-needed
