Repository content-services/content-sources-backend, pull requests merged in 2024-01, with the labels that each got.

#511 Fixes 3252: listing with limit=0 causes divide by 0 panic
  pkg/handler/api.go
  pkg/handler/api_test.go
Labels: qe-testing-needed, Ready for QE

#502 Fixes 3255: support pulp content guards
  configs/config.yaml.example
  db/migrations.latest
  db/migrations/20240102102721_AddContentGuardStatus.down.sql
  db/migrations/20240102102721_AddContentGuardStatus.up.sql
  pkg/cache/cache_mock.go
  pkg/config/config.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/models/snapshot.go
  pkg/pulp_client/content_guard.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/rpm_distributions.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/repository_snapshot.go
  scripts/header.sh
  scripts/turnpike_header.sh
  test/integration/snapshot_test.go
Labels: no-qe-needed

#505 Fixes 3232: add gh action to prevent out of order migrations
  .github/workflows/content-sources-actions.yml
Labels: no-qe-needed

#519 Fixes 3171: add gpg key path for red hat repos
  pkg/config/value_constraints.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
Labels: qe-testing-needed, Ready for QE

#526 Fixes 3170: use x-forward-host hdr for repo config
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
Labels: qe-testing-needed

#528 Refs 3372: switch to new s3 bucket name
  deployments/deployment.yaml
Labels: qe-testing-needed

#510 Fixes 2965: add create/fetch/list for templates
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240110100516_add_content_templates.down.sql
  db/migrations/20240110100516_add_content_templates.up.sql
  pkg/api/templates.go
  pkg/dao/interfaces.go
  pkg/dao/registry_mock.go
  pkg/dao/repositories_test.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/handler/api.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/repository_configuration.go
  pkg/models/template.go
  pkg/models/template_repository_configuration.go
  pkg/models/template_test.go
  pkg/seeds/seeds.go
Labels: qe-testing-needed, Ready for QE

#532 Refs 3372: fix s3 bucket name in code
  pkg/config/config.go
Labels: qe-testing-needed

#534 Fixes 3402: pass remote href on sync
  .rhcicd/pr_check.sh
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#517 Fixes 2982: add rpm search api for snapshots
  api/docs.go
  api/openapi.json
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  configs/config.yaml.example
  deployments/deployment.yaml
  go.mod
  go.sum
  pkg/api/repository_rpms.go
  pkg/config/config.go
  pkg/config/tang.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms.go
  pkg/dao/rpms_mock.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots.go
  pkg/handler/api.go
  pkg/handler/rpms.go
  pkg/handler/rpms_test.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/seeds/seeds.go
Labels: qe-testing-needed, Ready for QE

#529 Fixes 3357: Add UUID/URL filter for list repositories
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/cache/cache_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#538 Fixes 3423: add arm64 repos
  pkg/external_repos/redhat_repos.json
Labels: qe-testing-needed, Ready for QE

#520 Fixes 3144: check for orphan repo versions
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/repository_snapshot_test.go
Labels: no-qe-needed

#540 Refs 3423: fix arm64 repo arch
  pkg/external_repos/redhat_repos.json
Labels: qe-testing-needed

#541 Refs 3144: fix broken unit test
  pkg/tasks/repository_snapshot_test.go
Labels: no-qe-needed

#549 Fixes 3482: Do not run introspection tests
  .rhcicd/pr_check.sh
Labels: qe-testing-needed, Ready for QE

#550 Fixes 3278: migrate tasking to pgx
  go.mod
  go.sum
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/pgx_pool_wrapper.go
Labels: no-qe-needed

#552 Fixes 3492,3371: properly join repo to task
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
Labels: qe-testing-needed, Ready for QE
