Repository content-services/content-sources-backend, pull requests merged in 2024-04, with the labels that each got.

#624 Fixes 3876: remove unused path param in config.repo spec
  api/docs.go
  api/openapi.json
  pkg/handler/snapshots.go
Labels: qe-testing-needed, Ready for QE

#619 Fixes 3857: allow searching for popular repos
  pkg/config/config.go
  pkg/config/popular_repositories.go
  pkg/config/popular_repositories.json
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/popular_repositories.go
Labels: qe-testing-needed

#633 Fixes 3939: create/update RH repos as public
  pkg/dao/repository_configs.go
Labels: no-qe-needed

#634 Fixes 3940: handle pending snapshot task
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE

#595 Fixes 3490: update distributions for create/update templates
  cmd/content-sources/main.go
  cmd/dbmigrate/main.go
  cmd/external-repos/main.go
  db/migrations.latest
  db/migrations/20240403085352_add_distribution_href_to_templ_rc.down.sql
  db/migrations/20240403085352_add_distribution_href_to_templ_rc.up.sql
  pkg/config/tasks.go
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/suite_test.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/db/db.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/template_repository_configuration.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/rpm_distributions.go
  pkg/tasks/payloads/update_template_distributions.go
  pkg/tasks/update_template_distributions.go
  pkg/tasks/update_template_distributions_test.go
  test/integration/update_template_distributions_test.go
Labels: no-qe-needed

#638 Fixes 3766: add check for missing repos/snapshots
  pkg/dao/environments.go
  pkg/dao/environments_test.go
  pkg/dao/helpers.go
  pkg/dao/package_groups.go
  pkg/dao/package_groups_test.go
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/environments.go
  pkg/handler/package_groups.go
  pkg/handler/rpms.go
  pkg/handler/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#648 Fixes 4015: Bump tang to 0.0.6
  go.mod
  go.sum
Labels: qe-testing-needed, Ready for QE

#649 Fixes 4013,4008: Use custom lecho for enhanced logging
  go.mod
  go.sum
  pkg/middleware/extract_status.go
  pkg/router/route.go
Labels: no-qe-needed

#653 Fixes 4044: fix introspection of large repos
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#652 Fixes 3930: speed up slow rpm searching
  db/migrations.latest
  db/migrations/20240425110328_add_trgm_to_rpms.down.sql
  db/migrations/20240425110328_add_trgm_to_rpms.up.sql
Labels: qe-testing-needed, Ready for QE

#647 Fixes 3793: add make command for mockery
  README.md
  mk/includes.mk
  mk/mockery.mk
  pkg/cache/cache.go
  pkg/candlepin_client/interface.go
  pkg/dao/interfaces.go
  pkg/pulp_client/interfaces.go
  pkg/tasks/client/client.go
  pkg/tasks/queue/queue.go
Labels: no-qe-needed
