Repository content-services/content-sources-backend, pull requests merged in 2024-03, with the labels that each got.

#591 Fixes 3142: fixes default expiration on redis cache
  pkg/cache/redis.go
  pkg/config/config.go
Labels: qe-testing-needed, Ready for QE

#596 Fixes 3720: standardize snapshot routes
  api/docs.go
  api/openapi.json
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
Labels: qe-testing-needed, Ready for QE

#593 Fixes 3664: support listing/fetching RH tasks
  cmd/external-repos/main.go
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
  pkg/handler/task_info.go
Labels: qe-testing-needed, Ready for QE

#600 Fixes 3740: clean url during manual introspect
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#590 Fixes 2940: add snapshot rpm list api
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/api/rpms.go
  pkg/dao/interfaces.go
  pkg/dao/rpms.go
  pkg/dao/rpms_mock.go
  pkg/dao/rpms_test.go
  pkg/handler/rpms.go
  pkg/handler/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#604 Fixes 3773: Disable rbac testing
  .rhcicd/pr_check.sh
Labels: qe-testing-needed, Ready for QE

#606 Fixes 3775: handle nil response for domain updating
  pkg/pulp_client/domains.go
Labels: qe-testing-needed, Ready for QE

#607 Fixes 3668: remove err log for cache miss
  pkg/rbac/client_wrapper.go
Labels: no-qe-needed

#613 Fixes 3813: correct repo label for 9 appstream
  pkg/external_repos/redhat_repos.json
Labels: qe-testing-needed, Ready for QE

#610 Fixes 3602: api to check presence of packages in repos
  api/docs.go
  api/openapi.json
  pkg/api/content_units.go
  pkg/api/rpms.go
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms.go
  pkg/dao/rpms_mock.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates_mock.go
  pkg/handler/rpms.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#587 Fixes 3488: combine introspect and snapshot statuses
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240215104631_add_last_introspection_status.down.sql
  db/migrations/20240215104631_add_last_introspection_status.up.sql
  pkg/api/public_repositories.go
  pkg/api/repositories.go
  pkg/dao/metrics.go
  pkg/dao/metrics_test.go
  pkg/dao/repositories.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/suite_test.go
  pkg/external_repos/introspect.go
  pkg/external_repos/introspect_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/repository.go
  pkg/models/repository_configuration.go
  pkg/seeds/seeds.go
Labels: no-qe-needed

#616 Fixes 3845: Disable parallel testing in hms-integration
  deployments/testing-integration.yaml
Labels: qe-testing-needed
