Repository content-services/content-sources-backend, pull requests merged in 2024-11, with the labels that each got.

#844 Fixes 4716: Add "latest" snapshot distribution
  api/docs.go
  api/openapi.json
  pkg/api/repositories.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/helpers/pulp_distribution_helper.go
  pkg/tasks/helpers/pulp_distribution_helper_test.go
  pkg/tasks/repository_snapshot_test.go
  pkg/tasks/snapshot_helper.go
  pkg/tasks/update_latest_snapshot.go
  pkg/tasks/update_template_content.go
Labels: qe-testing-needed, Ready for QE

#869 Fixes 4610: don't trigger snapshot on adding slash to url
  pkg/dao/repository_configs.go
Labels: qe-testing-needed, Ready for QE

#875 Fixes 4927: add flag to prevent requeuing canceled tasks
  db/migrations.latest
  db/migrations/20241104115955_add_cancel_attempted_to_tasks.down.sql
  db/migrations/20241104115955_add_cancel_attempted_to_tasks.up.sql
  pkg/models/task_info.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
Labels: no-qe-needed

#877 Fixes 4775: add weekly cron for pulp orphan cleanup
  cmd/external-repos/main.go
  deployments/deployment.yaml
  pkg/dao/domain_dao_mock.go
  pkg/dao/domains.go
  pkg/dao/domains_test.go
  pkg/dao/interfaces.go
  pkg/utils/utils.go
Labels: no-qe-needed

#885 Fixes 4887: use livez for checking pulp connectivity
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/custom/collector_test.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/status.go
  scripts/mockery_comment_fix.sh
Labels: no-qe-needed

#887 Fixes 4991: introspect rhel 10 beta repositories
  pkg/external_repos/external_repos.json
Labels: qe-testing-needed

#879 Fixes 4964: add support for docker and importing arm repos
  mk/compose.mk
  pkg/external_repos/redhat_repos.json
Labels: no-qe-needed

#888 Fixes 4958: add rpm exact name search
  api/docs.go
  api/openapi.json
  pkg/api/content_units.go
  pkg/dao/environments.go
  pkg/dao/environments_test.go
  pkg/dao/package_groups.go
  pkg/dao/package_groups_test.go
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/rpms.go
Labels: qe-testing-needed, Ready for QE

#870 Fixes 3877: Add required fields for API spec requests
  api/docs.go
  api/openapi.json
  pkg/api/api.go
  pkg/api/pulp.go
  pkg/api/repositories.go
  pkg/api/repository_parameters.go
  pkg/api/rpms.go
  pkg/api/snapshots.go
  pkg/api/templates.go
  pkg/api/uploads.go
Labels: qe-testing-needed, Ready for QE

#900 Refs 4775: fix pulp-orphan-cleanup deployment
  deployments/deployment.yaml
Labels: no-qe-needed

#902 Fixes 5034: update latest snapshot after uploading content
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#893 Fixes 4925: fixup DBErrorToApi funcs
  pkg/dao/admin_tasks.go
  pkg/dao/admin_tasks_test.go
  pkg/dao/environments.go
  pkg/dao/package_groups.go
  pkg/dao/repository_configs.go
  pkg/dao/rpms.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: no-qe-needed

#906 Fixes 5052: refactor jobs and temp/repo association
  cmd/cleanup_versions/main.go
  cmd/content-sources/main.go
  cmd/dbmigrate/main.go
  cmd/external-repos/main.go
  cmd/jobs/main.go
  cmd/repair_latest/main.go
  deployments/deployment.yaml
  pkg/config/paths.go
  pkg/config/value_constraints.go
  pkg/dao/domains.go
  pkg/dao/domains_test.go
  pkg/dao/interfaces.go
  pkg/dao/rpms.go
  pkg/dao/suite_test.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/jobs/README.md
  pkg/jobs/retry_failed_tasks.go
  pkg/models/repository_configuration.go
  pkg/models/template.go
  pkg/tasks/candlepin_helpers.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#874 Fixes 4952: add snaps list with temp list/fetch
  api/docs.go
  api/openapi.json
  pkg/api/templates.go
  pkg/dao/interfaces.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/models/template_repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#908 Fixes 5058: separate set cancel from set cancel_attempted
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
Labels: no-qe-needed
