Repository content-services/content-sources-backend, pull requests merged in 2024-08, with the labels that each got.

#754 Fixes 4468: listing snapshot errata does not include CVEs
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#757 Fixes 4519: remove epel7 repo
  pkg/config/popular_repositories.json
  pkg/handler/popular_repositories_test.go
Labels: qe-testing-needed, Ready for QE

#758 Fixes 4413: create aggregate function in migration
  db/migrations.latest
  db/migrations/20240801113129_CreateAggrFunction.down.sql
  db/migrations/20240801113129_CreateAggrFunction.up.sql
  pkg/dao/package_groups.go
Labels: qe-testing-needed, Ready for QE

#760 Fixes 4416: listing tasks returns 500 for bad repo uuid
  pkg/dao/task_info.go
Labels: qe-testing-needed, Ready for QE

#764 Fixes 4539: fix indentation in example yaml config
  configs/config.yaml.example
Labels: no-qe-needed

#753 Fixes 4339,4371: add uploads API
  api/docs.go
  api/openapi.json
  cmd/content-sources/main.go
  go.mod
  go.sum
  pkg/api/uploads.go
  pkg/config/tasks.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots_test.go
  pkg/handler/pulp.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/repository.go
  pkg/models/repository_configuration.go
  pkg/pulp_client/artifacts.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/package.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/rbac/permission_map.go
  pkg/tasks/add_uploads.go
  pkg/tasks/repository_snapshot.go
  pkg/tasks/snapshot_helper.go
  pkg/test/handler/utils.go
  scripts/uploads.py
  test/integration/data/giraffe-0.67-2.noarch.rpm
  test/integration/pulp_upload_test.go
Labels: qe-testing-needed, Ready for QE

#769 Fixes 4422: edited repo returns incorrect snapshot task
  pkg/dao/environments.go
  pkg/dao/package_groups.go
  pkg/dao/rpms.go
  pkg/dao/task_info.go
Labels: qe-testing-needed, Ready for QE

#770 Fixes 4561: log/return domain on pulp task failures
  pkg/pulp_client/task.go
Labels: no-qe-needed

#763 Fixes 4091: add template docs
  README.md
  docs/pkg-graph.svg
  docs/workflows/snapshotting.md
  docs/workflows/templates.md
Labels: qe-testing-needed, Ready for QE

#778 Fixes 4290: update candlepin env name after template rename
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#773 Fixes 4432: log request body for server errors
  pkg/middleware/log_server_error_request.go
  pkg/middleware/log_server_error_request_test.go
  pkg/middleware/utils.go
  pkg/router/route.go
Labels: no-qe-needed

#766 Fixes 4313: update use_latest templates after new snapshot
  api/docs.go
  api/openapi.json
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  pkg/api/task_info.go
  pkg/api/templates.go
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/config/tasks.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/admin_tasks_test.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/templates.go
  pkg/models/task_info.go
  pkg/models/task_info_test.go
  pkg/seeds/seeds.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/update_latest_snapshot.go
  pkg/tasks/update_template_content.go
  pkg/tasks/update_template_content_test.go
  test/integration/delete_test.go
  test/integration/pulp_upload_test.go
  test/integration/snapshot_test.go
  test/integration/suite_test.go
  test/integration/update_latest_snapshot_test.go
  test/integration/update_repository_test.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#782 Fixes 4541: fix template patch endpoint error on empty date
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  test/integration/update_latest_snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#780 Fixes 4478: support cancel pending tasks
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/interfaces.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/task_info.go
  pkg/tasks/client/client.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/client/client_test.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/worker/worker.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#788 Refs 4478: release connection on Cancel
  pkg/tasks/queue/pgqueue.go
Labels: qe-testing-needed

#785 Fixes 4297: template API responds in UTC time
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: qe-testing-needed, Ready for QE

#783 Fixes 4549: add more tasks to task cleanup
  pkg/config/tasks.go
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
Labels: no-qe-needed

#790 Fixes 4523: use clock timestamp for started_at
  pkg/tasks/queue/pgqueue.go
Labels: qe-testing-needed, Ready for QE

#777 Fixes 4540: cancel template update tasks on delete
  pkg/handler/templates.go
  pkg/handler/templates_test.go
Labels: no-qe-needed

#781 Fixes 4548: add public upload create and upload chunk apis
  api/docs.go
  api/openapi.json
  pkg/api/pulp.go
  pkg/api/uploads.go
  pkg/handler/pulp.go
  pkg/handler/repositories.go
  pkg/handler/utils.go
  pkg/tasks/add_uploads.go
  scripts/uploads.py
  test/integration/pulp_upload_test.go
Labels: qe-testing-needed, Ready for QE

#793 Refs 4540: add update template task to cancel list
  pkg/config/tasks.go
Labels: no-qe-needed

#776 Fixes 4426: Remove NewRepositoryFiltering feature
  compose_files/pulp/docker-compose.yml
  pkg/config/config.go
  pkg/dao/repository_configs.go
  pkg/dao/snapshots_test.go
Labels: no-qe-needed

#775 Refs 4540: drop tasks repo_uuid
  db/migrations.latest
  db/migrations/20240814145645_DropTasksRepoUuid.down.sql
  db/migrations/20240814145645_DropTasksRepoUuid.up.sql
Labels: no-qe-needed
