Repository content-services/content-sources-backend, pull requests merged in 2024-12, with the labels that each got.

#905 Fixes 4928: fix worker task requeuing on start/stop
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgx_pool_wrapper.go
  test/integration/suite_test.go
Labels: no-qe-needed

#917 Fixes 5144: nightly job failing
  pkg/tasks/queue/pgqueue.go
Labels: no-qe-needed

#911 Fixes 5023: api to fetch template repo configs
  api/docs.go
  api/openapi.json
  pkg/cache/redis.go
  pkg/dao/interfaces.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/handler/admin_tasks_test.go
  pkg/handler/candlepin_test.go
  pkg/handler/environments_test.go
  pkg/handler/features_test.go
  pkg/handler/package_groups_test.go
  pkg/handler/popular_repositories_test.go
  pkg/handler/public_repositories_test.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/rpms_test.go
  pkg/handler/snapshots_test.go
  pkg/handler/task_info_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/middleware/enforce_identity.go
  pkg/middleware/enforce_identity_test.go
  pkg/middleware/rbac.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/router/route.go
  test/integration/import_export_repository_test.go
  test/integration/pulp_upload_test.go
Labels: qe-testing-needed, Ready for QE

#901 HMS-4747: automatic deletion of outdated snapshots
  api/docs.go
  api/openapi.json
  cmd/external-repos/main.go
  configs/config.yaml.example
  pkg/api/templates.go
  pkg/config/config.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: qe-testing-needed, Ready for QE

#913 HMS-5063: create job to cleanup missing domains
  cmd/jobs/main.go
  deployments/deployment.yaml
  deployments/jobs.yaml
  pkg/dao/domain_dao_mock.go
  pkg/dao/domains.go
  pkg/dao/domains_test.go
  pkg/dao/interfaces.go
  pkg/jobs/cleanup_missing_domains.go
Labels: no-qe-needed

#928 HMS-5202: don't always rerun failed snaps
  cmd/external-repos/main.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed

#918 HMS-5125: Add support for resumable downloads
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20241203143614_create_uploads_table.down.sql
  db/migrations/20241203143614_create_uploads_table.up.sql
  pkg/api/pulp.go
  pkg/api/uploads.go
  pkg/dao/interfaces.go
  pkg/dao/uploads.go
  pkg/dao/uploads_test.go
  pkg/handler/pulp.go
  pkg/handler/repositories.go
  pkg/models/uploads.go
  test/integration/pulp_upload_test.go
Labels: qe-testing-needed, Ready for QE
