Repository content-services/content-sources-backend, pull requests merged in 2024-02, with the labels that each got.

#554 Refs 3372: change pulp content path cache key
  pkg/cache/redis.go
Labels: qe-testing-needed

#547 Fixes 2966: Template update apis
  api/docs.go
  api/openapi.json
  pkg/api/templates.go
  pkg/cache/cache_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/template.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/seeds/seeds.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#548 Fixes 2017: add retry for failed tasks
  configs/config.yaml.example
  db/migrations.latest
  db/migrations/20240125132201_add_next_retry_time_to_tasks.down.sql
  db/migrations/20240125132201_add_next_retry_time_to_tasks.up.sql
  pkg/config/config.go
  pkg/models/task_info.go
  pkg/models/task_info_test.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/worker/worker.go
  pkg/tasks/worker/worker_pool.go
Labels: no-qe-needed

#536 Fixes 2983: add api for searching snap comps groups
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/api/repository_environments.go
  pkg/api/repository_package_groups.go
  pkg/api/snapshots.go
  pkg/dao/environments.go
  pkg/dao/environments_mock.go
  pkg/dao/environments_test.go
  pkg/dao/interfaces.go
  pkg/dao/package_groups.go
  pkg/dao/package_groups_mock.go
  pkg/dao/package_groups_test.go
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/api.go
  pkg/handler/environments.go
  pkg/handler/environments_test.go
  pkg/handler/features_test.go
  pkg/handler/package_groups.go
  pkg/handler/package_groups_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#556 Fixes 3517: job to retry existing failed tasks
  cmd/retry_failed_tasks/main.go
  deployments/deployment.yaml
  deployments/jobs.yaml
Labels: no-qe-needed

#555 Fixes 3346: new pattern for pulp response errors
  pkg/pulp_client/client.go
  pkg/pulp_client/content_guard.go
  pkg/pulp_client/domains.go
  pkg/pulp_client/orphans.go
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_publication.go
  pkg/pulp_client/rpm_remote.go
  pkg/pulp_client/rpm_repositories.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/pulp_client/task.go
Labels: no-qe-needed

#560 Fixes 3424: add label to repository configs
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240202124553_AddRepoConfigLabel.down.sql
  db/migrations/20240202124553_AddRepoConfigLabel.up.sql
  pkg/api/repositories.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/external_repos/redhat_repos.go
  pkg/models/repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#566 Fixes 3420: add service notify for templates
  cmd/content-sources/main.go
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/config/event.go
  pkg/dao/repository_configs.go
  pkg/dao/templates.go
  pkg/event/client.go
  pkg/event/client_test.go
  pkg/event/event_names.go
  pkg/external_repos/introspect.go
  pkg/kafka/config.go
  pkg/kafka/scram_client.go
  pkg/kafka/topics.go
  pkg/kafka/topics_test.go
Labels: no-qe-needed

#576 Refs 3255: fix escaping of bool
  deployments/deployment.yaml
Labels: no-qe-needed

#567 Fixes 3353: Snapshot inconsistent for API/UI
  pkg/dao/repository_configs.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#577 Refs 3255: correct mistaken default config value
  pkg/config/config.go
Labels: no-qe-needed

#575 Refs 3539: update yummy
  go.mod
  go.sum
Labels: qe-testing-needed

#579 Fixes 3612: add sslclient options to yum config
  pkg/dao/snapshots.go
Labels: qe-testing-needed, Ready for QE

#573 Fixes 3577: creation prevented on previously deleted item
  db/migrations.latest
  db/migrations/20240212140239_update_template_unique_constraint.down.sql
  db/migrations/20240212140239_update_template_unique_constraint.up.sql
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: qe-testing-needed, Ready for QE

#583 Fixes 3629: add org id to features config
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/config/config.go
  pkg/handler/features.go
  pkg/handler/features_test.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#588 Fixes 3654: Remove UUID from public repos
  README.md
  api/docs.go
  api/openapi.json
  pkg/api/public_repositories.go
  pkg/dao/repositories.go
  pkg/handler/public_repositories_test.go
Labels: qe-testing-needed, Ready for QE

#570 Fixes 3491: bootstrap candlepin connection
  cmd/candlepin/main.go
  configs/config.yaml.example
  configs/manifest.zip
  deployments/docker-compose.yml
  go.mod
  go.sum
  mk/compose.mk
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/client.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/interface.go
  pkg/candlepin_client/manifest.go
  pkg/candlepin_client/owner.go
  pkg/config/config.go
Labels: no-qe-needed

#568 Fixes 3292: Bump platform-go-middlewares to v2
  go.mod
  go.sum
  pkg/cache/redis.go
  pkg/handler/admin_tasks_test.go
  pkg/handler/environments_test.go
  pkg/handler/features.go
  pkg/handler/features_test.go
  pkg/handler/package_groups_test.go
  pkg/handler/popular_repositories_test.go
  pkg/handler/public_repositories_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/repository_parameters_test.go
  pkg/handler/rpms_test.go
  pkg/handler/snapshots_test.go
  pkg/handler/task_info_test.go
  pkg/handler/templates_test.go
  pkg/middleware/enforce_identity.go
  pkg/middleware/enforce_identity_test.go
  pkg/middleware/rbac_test.go
  pkg/rbac/client_wrapper.go
  pkg/rbac/client_wrapper_test.go
  pkg/router/route.go
  pkg/test/handler/utils.go
  pkg/test/mocks/rbac/rbac.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#586 Fixes 3533: Add DeleteTemplatesTask to RequeueFailedTasks
  pkg/config/tasks.go
  pkg/tasks/worker/worker_pool.go
Labels: no-qe-needed
