Repository content-services/content-sources-backend, pull requests merged in 2024-10, with the labels that each got.

#840 Fixes 4792: template tasks deleted causing invalid status
  pkg/dao/task_info.go
Labels: no-qe-needed

#842 Fixes 4821: expose URL on snapshot/for_date
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
Labels: qe-testing-needed, Ready for QE

#839 Fixes 4151: remove support for YYYY-MM-DD date formats
  pkg/api/snapshots.go
  pkg/dao/rpms.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots_test.go
  pkg/tasks/update_template_content.go
Labels: qe-testing-needed

#841 Fixes 4740: select correct snapshots for date selection
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
Labels: no-qe-needed

#848 Fixes 4851: remove pulp-web
  .github/workflows/content-sources-actions.yml
  README.md
  compose_files/pulp/assets/bin/nginx.sh
  compose_files/pulp/assets/nginx/nginx.conf.template
  compose_files/pulp/docker-compose.yml
  deployments/docker-compose.yml
  test/integration/snapshot_test.go
  test/integration/suite_test.go
  test/integration/update_latest_snapshot_test.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#851 Fixes 4797: no repo name or uuid in last_snapshot
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE

#846 Fixes 4825: add template attribute for when env is created
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20241011084507_AddEnvironmentCreated.down.sql
  db/migrations/20241011084507_AddEnvironmentCreated.up.sql
  pkg/api/templates.go
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/models/template.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#854 Fixes 4860: use timestamptz for date comparisons
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
Labels: qe-testing-needed, Ready for QE

#849 Fixes 4762: Add missing nil checks for pulp methods
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_remote.go
  pkg/pulp_client/status.go
  pkg/pulp_client/task.go
  pkg/pulp_client/uploads.go
  pkg/tasks/snapshot_helper.go
Labels: no-qe-needed

#850 Fixes 4852: close pgpool after integration tests
  cmd/content-sources/main.go
  cmd/external-repos/main.go
  pkg/handler/api.go
  pkg/handler/api_test.go
  pkg/middleware/rbac_test.go
  pkg/router/route.go
  pkg/router/route_test.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  test/integration/health_check_test.go
  test/integration/import_export_repository_test.go
  test/integration/pulp_upload_test.go
  test/integration/suite_test.go
Labels: no-qe-needed

#836 Fixes 4741: associate snapshots to templates directly
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20241018154315_associate_snaps_to_templates.down.sql
  db/migrations/20241018154315_associate_snaps_to_templates.up.sql
  pkg/dao/interfaces.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/models/template_repository_configuration.go
  pkg/seeds/seeds.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/update_latest_snapshot.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#853 Fixes 4853: fix gosec errors and enable gosec in CI
  .github/workflows/content-sources-actions.yml
  .golangci.yaml
  .pre-commit-config.yaml
  cmd/swagger2openapi/main.go
  pkg/candlepin_client/client.go
  pkg/dao/main_test.go
  pkg/db/db.go
  pkg/external_repos/introspect.go
  pkg/external_repos/store.go
  pkg/handler/main_test.go
  pkg/models/main_test.go
  pkg/pulp_client/client.go
  pkg/pulp_client/package.go
  pkg/tasks/add_uploads.go
  pkg/tasks/queue/main_test.go
  pkg/tasks/queue/pgqueue.go
  test/integration/health_check_test.go
  test/integration/import_export_repository_test.go
  test/integration/pulp_upload_test.go
Labels: no-qe-needed

#856 Fixes 4552: fix missing method bug with mock gen
  .mockery.yaml
  mk/mockery.mk
  pkg/cache/cache.go
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/interface.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates_mock.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue.go
  pkg/tasks/queue/queue_mock.go
  scripts/mockery_comment_fix.sh
Labels: no-qe-needed

#857 Refs 4739: adding new grafana visualization
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: no-qe-needed

#859 Refs 4863: Revert "remove support for YYYY-MM-DD formats"
  pkg/api/snapshots.go
  pkg/dao/rpms.go
  pkg/dao/snapshots_test.go
  pkg/dao/templates.go
  pkg/handler/snapshots_test.go
  pkg/tasks/update_template_content.go
Labels: qe-testing-needed

#860 Refs 4822: add cs prefix to domain name
  pkg/dao/domains.go
Labels: no-qe-needed

#866 Fixes 4897: env_created field reset after updating template
  pkg/dao/templates.go
  pkg/test/gpg/gpgkey.pub
  pkg/test/gpg/repomd.xml
  pkg/test/gpg/repomd.xml.asc
Labels: qe-testing-needed, Ready for QE
