Repository content-services/content-sources-backend, pull requests merged in 2024-06, with the labels that each got.

#685 Fixes 4195: check for multiple tags in openapi spec
  api/docs.go
  api/openapi.json
  cmd/lint_openapi/main.go
  mk/swag.mk
  pkg/handler/environments.go
  pkg/handler/package_groups.go
  pkg/handler/rpms.go
  pkg/handler/snapshots.go
Labels: no-qe-needed

#689 Fixes 4222: make repo list search case insensitive
  pkg/dao/repository_configs.go
Labels: qe-testing-needed, Ready for QE

#682 Fixes 4110,4209: set gpg & modular hotfixes in candlepin
  api/docs.go
  api/openapi.json
  cmd/content-sources/main.go
  deployments/deployment.yaml
  pkg/api/templates.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/candlepin_client/owner.go
  pkg/candlepin_client/pool.go
  pkg/candlepin_client/product.go
  pkg/config/config.go
  pkg/config/tasks.go
  pkg/dao/interfaces.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/repository_configuration.go
  pkg/seeds/seeds.go
  pkg/tasks/candlepin_helpers.go
  pkg/tasks/candlepin_helpers_test.go
  pkg/tasks/delete_templates.go
  pkg/tasks/delete_templates_test.go
  pkg/tasks/update_repository.go
  pkg/tasks/update_template_content.go
  test/integration/update_repository_test.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#695 Refs 4271: improve err logging for fetchRepoConfigsForRepo
  pkg/dao/repository_configs.go
Labels: qe-testing-needed

#697 Refs 4110: return from update task if no cp
  pkg/tasks/update_repository.go
Labels: qe-testing-needed

#686 Fixes 3600: delete distributions and env on template delete
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/interface.go
  pkg/config/config.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates_mock.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  test/integration/snapshot_test.go
Labels: no-qe-needed

#687 Fixes 4249: Reuse HTTP zest transport
  pkg/pulp_client/client.go
Labels: no-qe-needed

#699 Fixes 4267,4269: add user to template
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240610112037_add_user_to_template.down.sql
  db/migrations/20240610112037_add_user_to_template.up.sql
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/template.go
  pkg/seeds/seeds.go
  pkg/test/handler/utils.go
Labels: qe-testing-needed, Ready for QE

#705 Refs 3600: wrap template delete calls
  .github/workflows/content-sources-actions.yml
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/delete_templates.go
Labels: no-qe-needed

#694 Fixes 4272: template name should be editable
  api/docs.go
  api/openapi.json
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/handler/templates_test.go
  pkg/models/template.go
Labels: qe-testing-needed, Ready for QE

#701 Fixes 4285: add sort_by to /templates/uuid/errata
  api/docs.go
  api/openapi.json
  pkg/dao/rpms.go
  pkg/handler/rpms.go
Labels: qe-testing-needed, Ready for QE

#700 Fixes 4256: snapshot every hour
  cmd/external-repos/main.go
  deployments/deployment.yaml
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
Labels: no-qe-needed

#707 Fixes 4281: remove 8-stream from public repos
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/external_repos/external_repos.json
Labels: qe-testing-needed, Ready for QE

#710 Refs 4133: add types filter to admin tasks list
  pkg/api/api.go
  pkg/dao/admin_tasks.go
  pkg/dao/admin_tasks_test.go
  pkg/handler/admin_tasks.go
Labels: qe-testing-needed, Ready for QE

#711 Fixes 4292: filtering templates by repo uuids lists dups
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: qe-testing-needed, Ready for QE

#713 Refs 4256: change snapshot interval to 24 hours
  pkg/config/value_constraints.go
  pkg/dao/repository_configs.go
Labels: no-qe-needed

#714 Fixes 3942: valid meta_key shows no gpg key found
  api/docs.go
  api/openapi.json
  pkg/handler/repository_parameters.go
Labels: qe-testing-needed, Ready for QE

#712 Fixes 4320: add dashboard for all completing tasks
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: qe-testing-needed, Ready for QE

#717 Fixes 2246: fix conflict on guard creation
  pkg/pulp_client/content_guard.go
  pkg/pulp_client/domains.go
Labels: no-qe-needed

#721 Fixes 4334: lower parse filters log level
  pkg/handler/admin_tasks.go
  pkg/handler/api.go
  pkg/handler/task_info.go
  pkg/handler/templates.go
Labels: no-qe-needed

#715 Fixes 4090: add workflow docs
  README.md
  docs/workflows/introspection.md
  docs/workflows/snapshotting.md
Labels: qe-testing-needed, Ready for QE
