Repository content-services/content-sources-backend, pull requests merged in 2024-05, with the labels that each got.

#655 Fixes 3919: Add additional red hat repos
  pkg/external_repos/redhat_repos.json
Labels: qe-testing-needed, Ready for QE

#656 Fixes 4055: treat filter/page param parse as info
  pkg/dao/templates.go
  pkg/handler/admin_tasks.go
  pkg/handler/api.go
Labels: no-qe-needed

#645 Refs 2422: Add pending task metrics
  cmd/content-sources/main.go
  configs/config.yaml.example
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/logging.go
  pkg/dao/interfaces.go
  pkg/dao/metrics.go
  pkg/dao/metrics_mock.go
  pkg/dao/metrics_test.go
  pkg/dao/rpms_mock.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/metrics.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
Labels: no-qe-needed

#658 Refs 3565: add pulp connectivity metric
  cmd/content-sources/main.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/custom/collector_test.go
  pkg/instrumentation/metrics.go
Labels: no-qe-needed

#662 Refs 1738: set request id header on response
  pkg/middleware/request_id.go
Labels: no-qe-needed

#665 Refs 3565: correct pulp connectivity metric name
  pkg/instrumentation/metrics.go
Labels: no-qe-needed

#664 Refs 2422: Add pending tasks grafana
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: no-qe-needed

#659 Fixes 3832: update date type in /snapshots/for_date
  pkg/api/snapshots.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots_test.go
  pkg/tasks/update_template_distributions.go
Labels: qe-testing-needed, Ready for QE

#639 Fixes 3599: Add candlepin content for templates
  .github/workflows/content-sources-actions.yml
  cmd/candlepin/main.go
  cmd/content-sources/main.go
  db/migrations.latest
  db/migrations/20240513101357_add_label_constraint_to_repository_configuration.down.sql
  db/migrations/20240513101357_add_label_constraint_to_repository_configuration.up.sql
  go.mod
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/client.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/candlepin_client/manifest.go
  pkg/candlepin_client/owner.go
  pkg/candlepin_client/pool.go
  pkg/candlepin_client/product.go
  pkg/config/config.go
  pkg/config/tasks.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/repository_configuration.go
  pkg/pulp_client/status.go
  pkg/seeds/seeds.go
  pkg/tasks/payloads/update_template_content.go
  pkg/tasks/payloads/update_template_distributions.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/update_template_content.go
  pkg/tasks/update_template_content_test.go
  pkg/tasks/update_template_distributions.go
  test/integration/suite_test.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#663 Fixes 3655: Add api to list template rpms
  api/docs.go
  api/openapi.json
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms.go
  pkg/dao/rpms_mock.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/handler/rpms.go
  pkg/handler/rpms_test.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#674 Refs 4160: update label constraint migration to change label
  db/migrations/20240513101357_add_label_constraint_to_repository_configuration.up.sql
Labels: qe-testing-needed

#670 Fixes 4093: Override candlepin environment paths
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#673 Fixes 4009: snapshot errata should be sortable
  api/docs.go
  api/openapi.json
  go.mod
  go.sum
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/handler/rpms.go
Labels: qe-testing-needed, Ready for QE

#676 Fixes 4054: privatize repos without trailing slash
  db/migrations.latest
  db/migrations/20240522151803_cleanup_public_repos.down.sql
  db/migrations/20240522151803_cleanup_public_repos.up.sql
Labels: qe-testing-needed, Ready for QE

#680 Fixes 4208: add environment ID to template events/api
  api/docs.go
  api/openapi.json
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
Labels: qe-testing-needed, Ready for QE

#681 Refs 3125: allow delete repo during introspect/snapshot
  pkg/dao/interfaces.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#675 Fixes 3600: delete distributions and env on template delete
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/handler/templates.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/delete_templates.go
  pkg/tasks/delete_templates_test.go
  pkg/tasks/queue/queue_mock.go
  test/integration/suite_test.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed
