Repository content-services/content-sources-backend, pull requests merged in 2024-07, with the labels that each got.

#719 Fixes 3861: reject cancellation of certain task types
  pkg/config/tasks.go
  pkg/handler/task_info.go
  pkg/tasks/client/client.go
  pkg/tasks/client/client_test.go
  pkg/tasks/queue/queue.go
Labels: no-qe-needed

#718 Fixes 4103: add docs for tasking and metrics
  docs/metrics/metrics.md
  docs/tasking-system-architecture.md
  docs/tasking_system/images/api_process.svg
  docs/tasking_system/images/cancellation_logic.svg
  docs/tasking_system/images/consumer_process.svg
  docs/tasking_system/images/worker_loop.png
  docs/tasking_system/tasking_system.md
  pkg/tasks/introspect.go
Labels: qe-testing-needed, Ready for QE

#738 Fixes 4420: add ca support to candlepin client
  deployments/deployment.yaml
  pkg/candlepin_client/client.go
  pkg/config/config.go
Labels: no-qe-needed

#736 Fixes 4346: return task for introspect and snapshot APIs
  api/docs.go
  api/openapi.json
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#728 Fixes 4293: add support for upload only repos
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240627171711_allow_null_url.down.sql
  db/migrations/20240627171711_allow_null_url.up.sql
  pkg/api/repositories.go
  pkg/config/value_constraints.go
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/external_repos/redhat_repos.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/models/repository.go
  pkg/models/repository_configuration.go
  pkg/seeds/seeds.go
  test/integration/snapshot_test.go
  test/integration/update_repository_test.go
Labels: qe-testing-needed, Ready for QE

#745 Fixes 4431: detect env fetch 404 and use env type
  pkg/candlepin_client/environment.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#742 Fixes 4370: template create API allows blank arch/version
  pkg/dao/templates_test.go
  pkg/models/template.go
  pkg/models/template_test.go
  test/integration/snapshot_test.go
  test/integration/update_repository_test.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#732 Fixes 4294: snapshot on create for upload repo
  api/docs.go
  api/openapi.json
  pkg/api/repositories.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/handler/repositories.go
  pkg/models/repository.go
  pkg/tasks/repository_snapshot.go
  test/integration/snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#750 Refs 4294: fix db migration test
  mk/go-rules.mk
Labels: qe-testing-needed

#749 Fixes 4423: handle 404 on delete template
  pkg/candlepin_client/environment.go
Labels: qe-testing-needed, Ready for QE

#743 Fixes 4307: add use_latest parameter to template
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240716105614_add_use_latest_to_templates.down.sql
  db/migrations/20240716105614_add_use_latest_to_templates.up.sql
  go.mod
  go.sum
  pkg/api/templates.go
  pkg/dao/templates.go
  pkg/dao/templates_test.go
  pkg/models/template.go
  pkg/models/template_test.go
Labels: qe-testing-needed, Ready for QE

#747 Fixes 4312: support use_latest in update_template_content
  .github/workflows/content-sources-actions.yml
  pkg/config/tang.go
  pkg/dao/rpms.go
  pkg/tasks/update_template_content.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed, Ready for QE

#755 Fixes 4446: improve task context canceled logging
  cmd/content-sources/main.go
  pkg/dao/repository_configs.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/pgqueue.go
Labels: no-qe-needed
