Repository content-services/content-sources-backend, pull requests merged in 2024-09, with the labels that each got.

#797 Fixes 4666: lookup content sets instead of listing
  go.mod
  go.sum
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/content.go
  pkg/candlepin_client/interface.go
  pkg/tasks/update_template_content.go
Labels: qe-testing-needed, Ready for QE

#808 Fixes 4692: pass org id to FetchContentsByLabel
  pkg/tasks/update_template_content.go
Labels: no-qe-needed

#794 Fixes 4525: add subscription check endpoint
  configs/config.yaml.example
  go.sum
  pkg/api/candlepin.go
  pkg/cache/cache.go
  pkg/cache/cache_mock.go
  pkg/cache/noop.go
  pkg/cache/redis.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  pkg/candlepin_client/product.go
  pkg/config/config.go
  pkg/handler/api.go
  pkg/handler/candlepin.go
  pkg/handler/candlepin_test.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#798 Fixes 4672: on AddUploads add task to last_snapshot
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#789 Fixes 4681: Update to go 1.23
  .github/workflows/content-sources-actions.yml
  build/Dockerfile
  go.mod
  go.sum
  pkg/candlepin_client/client.go
  pkg/dao/task_info_test.go
  pkg/external_repos/introspect_test.go
  pkg/tasks/introspect.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
Labels: no-qe-needed

#806 Refs 4540: prevent requeue on exit for canceled task
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/worker/worker.go
Labels: no-qe-needed

#807 Refs 4540: fix task cancel issues
  pkg/dao/templates.go
  pkg/tasks/update_template_content.go
  pkg/tasks/worker/worker.go
Labels: no-qe-needed

#809 Fixes 4665: improve error responses for upload apis
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info_mock.go
  pkg/dao/templates_mock.go
  pkg/handler/pulp.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/uploads.go
  pkg/tasks/add_uploads.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
Labels: qe-testing-needed, Ready for QE

#796 Fixes 4571: list snapshots by template with repo information
  api/docs.go
  api/openapi.json
  pkg/api/snapshots.go
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots.go
Labels: qe-testing-needed, Ready for QE

#814 Fixes 4712: add content override for sslverifystatus
  pkg/candlepin_client/content.go
  pkg/tasks/candlepin_helpers.go
  pkg/tasks/candlepin_helpers_test.go
  test/integration/update_template_content_test.go
Labels: qe-testing-needed

#815 Fixes 4707: add origin to RepoConfig dao tests
  pkg/dao/repositories_test.go
  pkg/dao/repository_configs_test.go
Labels: qe-testing-needed, Ready for QE

#791 Fixes 4614: change time format to be always UTC
  pkg/config/config.go
  pkg/dao/admin_tasks_test.go
  pkg/dao/environments_test.go
  pkg/dao/metrics_test.go
  pkg/dao/package_groups_test.go
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info_test.go
  pkg/models/base.go
  pkg/models/repository.go
  pkg/models/repository_configuration.go
  pkg/models/snapshot.go
  pkg/models/task_info.go
  pkg/models/template.go
  pkg/models/template_repository_configuration.go
Labels: qe-testing-needed, Ready for QE

#811 Fixes 4644: task info response shows template name and uuid
  api/docs.go
  api/openapi.json
  pkg/api/task_info.go
  pkg/dao/repository_configs.go
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
  pkg/handler/task_info.go
  pkg/handler/task_info_test.go
  pkg/models/task_info.go
Labels: qe-testing-needed

#817 Fixes 4729: stop adding guard to RH repos
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/pulp_client/rpm_distributions.go
  pkg/tasks/helpers/pulp_distribution_helper.go
  pkg/tasks/helpers/pulp_distribution_helper_test.go
  pkg/tasks/update_latest_snapshot.go
  pkg/tasks/update_template_content.go
Labels: no-qe-needed

#812 Fixes 4185: retain systems when deleting template
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/candlepin_client/consumer.go
  pkg/candlepin_client/environment.go
  pkg/candlepin_client/interface.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#824 Fixes 4735: snapshot repos even if last task was deleted
  db/migrations.latest
  db/migrations/20240917101025_AddLastSnapshotTaskConstraint.down.sql
  db/migrations/20240917101025_AddLastSnapshotTaskConstraint.up.sql
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/task_info_test.go
  pkg/tasks/queue/pgqueue.go
Labels: no-qe-needed

#827 Fixes 4745: use domain list to detect pulp is up
  pkg/handler/api.go
Labels: no-qe-needed

#818 Fixes 4645: show last error for templates
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20240919154238_add_template_status_fields.down.sql
  db/migrations/20240919154238_add_template_status_fields.up.sql
  pkg/api/templates.go
  pkg/dao/interfaces.go
  pkg/dao/templates.go
  pkg/dao/templates_mock.go
  pkg/dao/templates_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/models/template.go
  pkg/tasks/update_latest_snapshot.go
  pkg/tasks/update_template_content.go
Labels: qe-testing-needed, Ready for QE

#831 Refs 4745: lookup domain on init containers
  cmd/external-repos/main.go
Labels: no-qe-needed

#830 Fixes 4643: return object name for red hat task fetch
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
Labels: qe-testing-needed, Ready for QE

#800 Fixes 4445: add apis to bulk import/export custom repos
  api/docs.go
  api/openapi.json
  pkg/api/repositories.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  test/integration/import_export_repository_test.go
Labels: qe-testing-needed, Ready for QE

#828 Fixes 4713: improve cancel behavior
  pkg/cache/cache_mock.go
  pkg/candlepin_client/candlepin_client_mock.go
  pkg/dao/admin_tasks_mock.go
  pkg/dao/domain_dao_mock.go
  pkg/dao/environments_mock.go
  pkg/dao/interfaces.go
  pkg/dao/metrics_mock.go
  pkg/dao/package_groups_mock.go
  pkg/dao/repositories_mock.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/rpms_mock.go
  pkg/dao/snapshots_mock.go
  pkg/dao/task_info.go
  pkg/dao/task_info_mock.go
  pkg/dao/task_info_test.go
  pkg/dao/templates_mock.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/handler/templates.go
  pkg/handler/templates_test.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/pulp_global_client_mock.go
  pkg/tasks/client/client_mock.go
  pkg/tasks/queue/queue_mock.go
  pkg/tasks/update_template_content.go
  pkg/tasks/worker/worker.go
Labels: no-qe-needed

#834 Fixes 4777: remove custom param in list candlepin products
  pkg/candlepin_client/product.go
Labels: no-qe-needed
