Repository content-services/content-sources-backend, pull requests merged in 2025-02, with the labels that each got.

#953 HMS-5390: omit null values in upload response
  api/docs.go
  api/openapi.json
  pkg/api/uploads.go
  pkg/handler/repositories.go
Labels: qe-testing-needed, Ready for QE

#957 HMS-5057: query RH repos based on account's features
  api/docs.go
  api/openapi.json
  cmd/external-repos/main.go
  configs/config.yaml.example
  deployments/deployment.yaml
  pkg/api/api.go
  pkg/api/repositories.go
  pkg/cache/cache.go
  pkg/cache/cache_mock.go
  pkg/cache/noop.go
  pkg/cache/redis.go
  pkg/config/config.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_test.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_test.go
  pkg/dao/task_info_test.go
  pkg/dao/templates.go
  pkg/feature_service_client/client.go
  pkg/feature_service_client/feature_service_client_mock.go
  pkg/feature_service_client/features.go
  pkg/handler/api.go
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
Labels: qe-testing-needed, Ready for QE

#951 HMS-5293: add list feature content
  pkg/api/admin_task.go
  pkg/feature_service_client/features.go
  pkg/handler/admin_tasks.go
  pkg/handler/admin_tasks_test.go
  pkg/handler/api.go
Labels: no-qe-needed

#958 HMS-5379: add metrics for templates
  pkg/config/tasks.go
  pkg/dao/interfaces.go
  pkg/dao/metrics.go
  pkg/dao/metrics_mock.go
  pkg/dao/metrics_test.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/metrics.go
  pkg/seeds/seeds.go
Labels: no-qe-needed

#956 HMS-5287: Add playwright and github action to backend
  .github/workflowScripts/getFrontendRepo.sh
  .github/workflowScripts/waitForBackend.sh
  .github/workflows/content-sources-actions.yml
  .github/workflows/playwright-actions.yml
  .github/workflows/title.yml
  .gitignore
  KubernetesLocalProcessConfig.example.yaml
  README.md
  _playwright-tests/.nvmrc
  _playwright-tests/example.env
  _playwright-tests/package.json
  _playwright-tests/playwright.config.ts
  _playwright-tests/readme.md
  _playwright-tests/tests/API/CheckGetFeatures.spec.ts
  _playwright-tests/tests/auth.setup.ts
  _playwright-tests/tests/helpers/loginHelpers.tsx
  _playwright-tests/tsconfig.json
  _playwright-tests/yarn.lock
  buildspec.yml
  configs/config.yaml.example
  mk/README.md
  mk/compose.mk
  mk/db.mk
  mk/includes.mk
  mk/playwright.mk
  pkg/candlepin_client/owner.go
  scripts/create_env_if_not_exist.sh
  scripts/get_go_version.sh
Labels: qe-testing-needed, Ready for QE

#952 HMS-5225: retry failed RH snapshots sooner
  api/docs.go
  api/openapi.json
  db/migrations.latest
  db/migrations/20250123134950_add_failed_snapshot_count.down.sql
  db/migrations/20250123134950_add_failed_snapshot_count.up.sql
  pkg/api/repositories.go
  pkg/config/value_constraints.go
  pkg/dao/interfaces.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/models/repository_configuration.go
  pkg/tasks/queue/pgqueue.go
  pkg/tasks/queue/pgqueue_test.go
  pkg/tasks/repository_snapshot.go
Labels: qe-testing-needed, Ready for QE

#964 HMS-5379: add template metrics to grafana
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: no-qe-needed

#975 HMS-4747: add missing option to job deployment
  deployments/deployment.yaml
Labels: qe-testing-needed

#955 HMS-5415: drop content_guard_added column
  db/migrations.latest
  db/migrations/20250128083413_drop_snapshot_cguard_added.down.sql
  db/migrations/20250128083413_drop_snapshot_cguard_added.up.sql
Labels: no-qe-needed

#986 HMS-5527: add request org_id to log parse
  pkg/jobs/transform_pulp_logs.go
  pkg/jobs/transform_pulp_logs_test.go
Labels: no-qe-needed

#984 HMS-5526: ignore canceled ctx for failed_snapshot_count
  pkg/pulp_client/status.go
  pkg/tasks/repository_snapshot.go
Labels: no-qe-needed

#985 HMS-5162: replace fedorapeople comps repos with github fixtures
  .github/workflows/playwright-actions.yml
  _playwright-tests/tests/API/Repositories.spec.ts
  test/integration/delete_test.go
  test/integration/update_latest_snapshot_test.go
  test/integration/update_template_content_test.go
Labels: no-qe-needed

#993 HMS-5396: Log error if log event is malformed
  pkg/jobs/transform_pulp_logs.go
Labels: no-qe-needed

#988 HMS-5522: cleanup snapshots even if partially deleted
  cmd/external-repos/main.go
  pkg/dao/interfaces.go
  pkg/dao/snapshots.go
  pkg/dao/snapshots_mock.go
  pkg/dao/snapshots_test.go
  pkg/handler/snapshots.go
  pkg/handler/snapshots_test.go
  pkg/pulp_client/interfaces.go
  pkg/pulp_client/pulp_client_mock.go
  pkg/pulp_client/rpm_distributions.go
  pkg/pulp_client/rpm_repository_version.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/delete_repository_snapshots_test.go
  pkg/tasks/delete_snapshots.go
  pkg/tasks/delete_snapshots_test.go
  pkg/tasks/delete_templates.go
  pkg/tasks/snapshot_helper.go
  pkg/tasks/update_template_content.go
Labels: no-qe-needed
