Repository content-services/content-sources-backend, pull requests merged in 2025-07, with the labels that each got.

#1137 HMS-8635: Add bulk import repositories test
  _playwright-tests/tests/API/Repositories.spec.ts
Labels: qe-testing-needed, Ready for QE

#1140 HMS-8774: Test to verify bulkExportRepositories api
  _playwright-tests/tests/API/Repositories.spec.ts
Labels: qe-testing-needed

#1144 HMS-8834: add turnpike via composite for red hat repos
  pkg/clients/pulp_client/content_guard.go
  pkg/clients/pulp_client/interfaces.go
  pkg/clients/pulp_client/pulp_client_mock.go
  pkg/external_repos/snapshotted_repos/high_availability-x86_64.json
  pkg/tasks/helpers/pulp_distribution_helper.go
  pkg/tasks/helpers/pulp_distribution_helper_test.go
  test/integration/snapshot_test.go
Labels: no-qe-needed

#1155 HMS-8916: Persist pulp database for compose-down
  compose_files/pulp/docker-compose.yml
Labels: qe-testing-needed, Ready for QE
