Repository content-services/content-sources-backend, pull requests merged in 2025-03, with the labels that each got.

#1004 HMS-5585: do not delete last template update tasks
  pkg/dao/task_info.go
  pkg/dao/task_info_test.go
Labels: qe-testing-needed, Ready for QE

#980 HMS-5432: API - Playwright POC - Templating
  _playwright-tests/tests/API/TemplateCRUD.spec.ts
  _playwright-tests/tests/API/helpers/apiHelpers.tsx
  _playwright-tests/tests/API/helpers/deleteRepositories.tsx
  _playwright-tests/tests/API/helpers/repoHelpers.tsx
Labels: qe-testing-needed, Ready for QE

#1007 HMS-5595: Add test for repo parameters validation api
  _playwright-tests/tests/API/Repositories.spec.ts
Labels: qe-testing-needed

#996 HMS-5551: use prefix match for rpm search
  go.mod
  go.sum
  pkg/dao/rpms.go
  pkg/dao/rpms_test.go
Labels: qe-testing-needed, Ready for QE

#1028 HMS-5395: add metrics for cert expiration
  pkg/config/certificates.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/metrics.go
Labels: no-qe-needed

#1037 HMS-5395: add all cert expirations to grafana
  deployments/dashboards/grafana-dashboard-content-sources.configmap.yaml
Labels: no-qe-needed

#1008 HMS-5613,HMS-5614: search rpms and add popular repo tests
  _playwright-tests/tests/API/PopularRepos.spec.ts
  _playwright-tests/tests/API/Repositories.spec.ts
  _playwright-tests/tests/API/helpers/apiHelpers.tsx
Labels: qe-testing-needed, Ready for QE

#1038 HMS-5303: remove ansible repositories for snapshotting
  cmd/external-repos/main.go
  pkg/clients/candlepin_client/interface.go
  pkg/dao/interfaces.go
  pkg/dao/repositories.go
  pkg/dao/repositories_mock.go
  pkg/dao/repositories_test.go
  pkg/dao/repository_configs.go
  pkg/dao/repository_configs_mock.go
  pkg/dao/repository_configs_test.go
  pkg/external_repos/external_repos.json
  pkg/external_repos/redhat_repos.json
  pkg/handler/repositories.go
  pkg/handler/repositories_test.go
  pkg/tasks/delete_repository_snapshots.go
  pkg/tasks/update_template_content.go
  test/integration/delete_test.go
  test/integration/suite_test.go
  test/integration/update_latest_snapshot_test.go
Labels: qe-testing-needed, Ready for QE

#1039 HMS-5395: remove RHCertExpiryDays metric
  pkg/instrumentation/custom/collector.go
  pkg/instrumentation/metrics.go
Labels: no-qe-needed
